In [ ]:
import tensorflow as tf

t1 = tf.constant([[1 , 2], [3, 4], [5, 6]])
output = t1[:, 0]

print(output.shape)

indices = [[0, 0]]  # A list of coordinates to update.

values = [1]  # A list of values corresponding to the respective
                # coordinate in indices.


delta = tf.SparseTensor(indices, values, t1.shape)
zeros = tf.zeros_like(t1)
result = zeros + tf.sparse_tensor_to_dense(delta)

with tf.Session() as sess:
  print(t1.shape)
  print(sess.run(output))
  print(sess.run(tf.shape(t1)[0]))
  print(sess.run(result))
  print()


# helper = np.zeros((3, 2))
# helper[:, 0] = 1
#
# print(helper)


array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [1]:
import numpy as np

np.full(200, 15)


array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [5]:
import numpy as np

t = np.array([0, 1, 15, 0])
t = (t > 0).astype(int)
t

array([0, 1, 1, 0])

In [10]:
binary_classification = True
x = 2 if binary_classification else 15

x

2

In [59]:
import numpy as np
import tensorflow as tf

batch_size = 5
max_policy_history_length = 3
n_output = 2

g = tf.Graph()

with g.as_default():
    a = tf.constant(np.random.normal(0, 1, size=[batch_size, max_policy_history_length, n_output]))
    b = tf.Variable(initial_value=tf.reshape(tensor=a, shape=[batch_size * max_policy_history_length * n_output]))
    c = tf.scatter_update(b, [i * max_policy_history_length * n_output for i in range(batch_size)], [0 for j in range(batch_size)])
    d = tf.reshape(tensor=c, shape= [batch_size, max_policy_history_length, n_output]) 
with tf.Session(graph=g) as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(a))
    #print(sess.run(b))
    #print(sess.run(c))
    print(sess.run(d))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[[-0.81199294 -0.95736281]
  [-0.10020636 -0.17498547]
  [ 0.37001408  0.20169207]]

 [[-1.16332337  0.01598867]
  [ 1.03221142 -0.07417807]
  [-0.47099898  0.85285323]]

 [[ 1.26148773 -1.95553698]
  [-0.61355427 -0.43529128]
  [ 0.95160506  1.95446399]]

 [[ 0.9351669  -0.20272635]
  [-0.03296645 -1.18031477]
  [-0.18714346 -0.08218005]]

 [[ 2.62357858 -0.78848738]
  [ 0.11761094  0.62897519]
  [ 0.64231895 -0.62611121]]]
[[[ 0.         -0.95736281]
  [-0.10020636 -0.17498547]
  [ 0.37001408  0.20169207]]

 [[ 0.          0.01598867]
  [ 1.03221142 -0.07417807]
  [-0.47099898  0.85285323]]

 [[ 0.         -1.95553698]
  [-0.61355427 -0.43529128]
  [ 0.95160506  1.95446399]]

 [[ 0.         -0.20272635]
  [-0.03296645 -1.18031477]
  [-0.18714346 -0.08218005]]

 [[ 0.         -0.78848738]
  [ 0.11761094  0.62897519]
  [ 0.64231895 -0.62611121]]]


In [1]:
import tensorflow as tf
import numpy as np

noise_dimensions = 100
batch_size = 5
g_n_outputs = 2
max_policy_history_length = 3

tf.reset_default_graph()
tf.set_random_seed(42)

noise = tf.placeholder(tf.float32, [None, max_policy_history_length, noise_dimensions], name='noise')
noise_seq_length = tf.placeholder(tf.int32, [None], name='noise_seq_length')
  
    
def generator(noise, batch_size, n_outputs, max_seq_length, seq_length):
    n_layers = 3
    n_neurons = 200

    with tf.variable_scope("t_generator"):
        layers = [tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,
                                              activation=tf.nn.relu)
                  for layer in range(n_layers)]
        multi_layer_cell = tf.contrib.rnn.MultiRNNCell(layers, state_is_tuple=False)
        outputs, states = tf.nn.dynamic_rnn(cell=multi_layer_cell, inputs=noise, sequence_length=seq_length, dtype=tf.float32)

        dense = tf.layers.dense(outputs, n_outputs)
        # Let's make sure the initial value at [:, 0, 1] is 0 (current capital at policy inception)
        flat = tf.reshape(tensor=dense, shape=[batch_size * max_policy_history_length * n_outputs])
        flat2 = tf.Variable(initial_value=tf.zeros_like(flat), trainable=False, name="Scheisse")
        flat3 = tf.assign(ref=flat2, value=flat)
        flat4 = tf.scatter_update(flat3, [1 + i * max_policy_history_length * n_outputs for i in range(batch_size)],
                                         [0 for j in range(batch_size)])
        logits = tf.reshape(tensor=flat4, shape=[batch_size, max_policy_history_length, n_outputs])
    
        print(logits)    
    return logits


g_data = generator(noise=noise, batch_size=batch_size, n_outputs=g_n_outputs, 
                       max_seq_length=max_policy_history_length, seq_length=noise_seq_length)

noise_batch = np.random.normal(0, 1, size=[batch_size, max_policy_history_length, noise_dimensions])
noise_seq_length_batch = np.full(batch_size, max_policy_history_length)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

print(sess.run(g_data, feed_dict={noise: noise_batch, noise_seq_length: noise_seq_length_batch}))



Tensor("t_generator/Reshape_1:0", shape=(5, 3, 2), dtype=float32)
[[[ 0.24061829  0.        ]
  [ 0.13354699 -0.36437303]
  [ 0.31483549 -0.2814326 ]]

 [[ 0.23679543  0.        ]
  [ 0.25634789 -0.21235539]
  [ 0.42624265 -0.25352508]]

 [[ 0.17284954  0.        ]
  [ 0.32191426 -0.2703692 ]
  [ 0.05656416 -0.48483819]]

 [[ 0.16864222  0.        ]
  [ 0.31050789 -0.29020679]
  [ 0.37562567 -0.34442496]]

 [[-0.04074495  0.        ]
  [ 0.17831247  0.03321953]
  [ 0.0709499  -0.21526265]]]


In [6]:
import numpy as np
import tensorflow as tf

def do_something(x, s1, s2, s3):
    for i in range(s1):
        x[i, 0, 0] = 0.0
    
    return x 

batch_size = 5
max_seq_length = 3
n_outputs = 2

g = tf.Graph()

with g.as_default():
    a = tf.constant(np.random.normal(0, 1, size=[batch_size, max_seq_length, n_outputs]))
    b = tf.py_func(do_something, [a, batch_size, max_seq_length, n_outputs], tf.float64)    
with tf.Session(graph=g) as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(a))
    print(sess.run(b))


Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[[ 0.69610407  0.12660089]
  [ 0.09215754  0.58294227]
  [-0.87823905  0.7732932 ]]

 [[-0.16305498  0.33017592]
  [-0.18461336  0.61272635]
  [ 0.65350396  0.13504304]]

 [[ 0.16052591 -0.19250083]
  [-0.51150417 -0.67703675]
  [ 2.26027099 -0.02618426]]

 [[-0.07672129 -0.718167  ]
  [ 0.60350131  2.90098423]
  [ 0.12369684  0.03033765]]

 [[-0.09879402  0.29269795]
  [ 0.59075546 -0.74791095]
  [-1.41866875 -0.55138431]]]
[[[ 0.          0.12660089]
  [ 0.09215754  0.58294227]
  [-0.87823905  0.7732932 ]]

 [[ 0.          0.33017592]
  [-0.18461336  0.61272635]
  [ 0.65350396  0.13504304]]

 [[ 0.         -0.19250083]
  [-0.51150417 -0.67703675]
  [ 2.26027099 -0.02618426]]

 [[ 0.         -0.718167  ]
  [ 0.60350131  2.90098423]
  [ 0.12369684  0.03033765]]

 [[ 0.          0.29269795]
  [ 0.59075546 -0.74791095]
  [-1.41866875 -0.55138431]]]


In [1]:
size_batch = 10
max_length_policy_history = 15
n_inputs = 2
runtime = 5

import numpy as np

Z_batch = np.full(shape=[size_batch, max_length_policy_history, n_inputs], fill_value=0.0)
seq_length_z_batch = np.full(shape=size_batch, fill_value=1 + runtime * 2)

init_z_batch = np.full(shape=[size_batch, 2], fill_value=0.0)
init_z_batch[:, 0] = np.random.uniform(low=1000.0, high=1500.0, size=size_batch)
init_z_batch[:, 1] = np.random.randint(low=1, high=4, size=size_batch) * 0.01 + 0.02
#init_z_batch = np.full(shape=size_batch, fill_value=1270.0)
Z_batch[:, 0, 0] = init_z_batch[:, 0]
Z_batch[:, 0, 1] = init_z_batch[:, 1]




print(Z_batch)
print(seq_length_z_batch)

[[[  1.00859221e+03   3.00000000e-02]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[  1.07676271e+03   3.00000000e-02]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]
  [  0.000

In [17]:
import numpy as np
import tensorflow as tf

batch_size = 5
max_policy_history_length = 3
n_output = 2

tf.reset_default_graph()
tf.set_random_seed(42)
np.random.seed(42)

n_inputs = 2
n_neurons = 2

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])
X2 = tf.placeholder(tf.float32, [None, n_inputs])


iWx = [[1.0, 0.0], [0.0, 0.0]]
iWy = [[1.0, 1.0], [1.0, 1.0]]

Wx = tf.Variable(initial_value=iWx, dtype=tf.float32)
Wy = tf.Variable(initial_value=iWy, dtype=tf.float32)
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.nn.relu(tf.matmul(X0, Wx) + b)
Y1 = tf.nn.relu(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)
Y2 = tf.nn.relu(tf.matmul(Y1, Wy) + tf.matmul(X2, Wx) + b)


init = tf.global_variables_initializer()

X0_batch = np.array([[1250, 0.3]]) # t = 0
X1_batch = np.array([[0, 0]]) # t = 1
X2_batch = np.array([[0, 0]]) # t = 1


with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val, Y2_val = sess.run([Y0, Y1, Y2], feed_dict={X0: X0_batch, X1: X1_batch, X2: X2_batch})

    print(Y0_val)
    print(Y1_val)
    print(Y2_val)

[[ 1250.     0.]]
[[ 1250.  1250.]]
[[ 2500.  2500.]]


In [10]:
import numpy as np

s = np.random.randint(low=1, high=4, size=10)
print(s)

[1 1 1 2 3 2 3 2 1 1]
