In [13]:
import support_functions as sf

sf.generate_very_simple_portfolio_history(no_of_policies=10000, runtime=5)

In [14]:
policy_histories = sf.load_troubled_life_policy_data()
#policy_histories

In [15]:
policy_histories, history_lengths, max_history_length = sf.prepare_troubled_life_policy_data(policy_histories=policy_histories)
#policy_histories


In [16]:
# Extract features and labels from dataset as numpy.ndarray(s)
policy_histories_labels = policy_histories['troubled'].as_matrix()
policy_histories_features = policy_histories[['premium', 'current_capital']].as_matrix()

# Reshape features from (overall_no_of_histories, 2) to (overall_no_of_policies, maximum_history_length, 2)
policy_histories_features = policy_histories_features.reshape((policy_histories.index.levels[0].shape[0], max_history_length, -1))

# Reshape labels from (overall_no_of_histories) to (overall_no_of_policies, maximum_history_length) and take maximum of each row (0 or 1)
policy_histories_labels = policy_histories_labels.reshape(policy_histories.index.levels[0].shape[0], -1).max(axis=1)

history_lengths = history_lengths[:,1]

#policy_histories_features, policy_histories_labels, history_lengths

In [17]:
import tensorflow as tf

tf.reset_default_graph()
tf.set_random_seed(42)

n_steps = max_history_length
n_inputs = 2

n_neurons = 100
n_outputs = 2

learning_rate = 0.001

# Placeholders for our input sequences
seq_length = tf.placeholder(tf.int32, [None])
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.int32, [None])

# A single RNN layer of n_neurons neurons
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32, sequence_length=seq_length)

# We feed the layer's output of the last timestep into a fully connected layer of 2 neurons
# (1 per class, troubled or not). Softmax layer is next
logits = tf.layers.dense(states, n_outputs)
y_pred = tf.argmax(tf.nn.softmax(logits), axis=1)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)
#xentropy = y - y_pred
#xentropy = tf.abs(xentropy)

# Loss function and Adam Optimizer
loss = tf.reduce_mean(tf.cast(xentropy, tf.float32))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

correct = tf.nn.in_top_k(logits, y, 1)
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

init = tf.global_variables_initializer()


In [19]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

n_epochs = 100
batch_size = 1000

X_batch = policy_histories_features
y_batch = policy_histories_labels
seq_length_batch = history_lengths

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for i in range(policy_histories_labels.shape[0] // batch_size):
            X_batch = policy_histories_features[i * batch_size : (i + 1) * batch_size]
            y_batch = policy_histories_labels[i * batch_size : (i + 1) * batch_size]
            seq_length_batch = history_lengths[i * batch_size : (i + 1) * batch_size]
            
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
            #print(outputs.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch}))
        #print(logits.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch}))
        y_batch_pred = y_pred.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        acc_train = accuracy.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        #acc_test = accuracy.eval(feed_dict={X: X_test, y: y_test})
        print(epoch, "Train accuracy:", acc_train)#, "Test accuracy:", acc_test)
        print(loss.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch}))
        print(confusion_matrix(y_batch, y_batch_pred))
        print(classification_report(y_batch, y_batch_pred, target_names=['ok', 'troubled']))




0 Train accuracy: 0.776
358.37
[[776   0]
 [224   0]]
             precision    recall  f1-score   support

         ok       0.78      1.00      0.87       776
   troubled       0.00      0.00      0.00       224

avg / total       0.60      0.78      0.68      1000

1 Train accuracy: 0.776
50.6838
[[776   0]
 [224   0]]
             precision    recall  f1-score   support

         ok       0.78      1.00      0.87       776
   troubled       0.00      0.00      0.00       224

avg / total       0.60      0.78      0.68      1000



/Users/gopora/MyStuff/Dev/miniconda3/envs/pie35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


2 Train accuracy: 0.776
29.3997
[[776   0]
 [224   0]]
             precision    recall  f1-score   support

         ok       0.78      1.00      0.87       776
   troubled       0.00      0.00      0.00       224

avg / total       0.60      0.78      0.68      1000

3 Train accuracy: 0.179
25.724
[[  0 776]
 [ 45 179]]
             precision    recall  f1-score   support

         ok       0.00      0.00      0.00       776
   troubled       0.19      0.80      0.30       224

avg / total       0.04      0.18      0.07      1000

4 Train accuracy: 0.866
3.6167
[[776   0]
 [134  90]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       776
   troubled       1.00      0.40      0.57       224

avg / total       0.89      0.87      0.84      1000



5 Train accuracy: 0.866
3.85846
[[776   0]
 [134  90]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       776
   troubled       1.00      0.40      0.57       224

avg / total       0.89      0.87      0.84      1000

6 Train accuracy: 0.868
3.10776
[[776   0]
 [132  92]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       776
   troubled       1.00      0.41      0.58       224

avg / total       0.89      0.87      0.85      1000

7 Train accuracy: 0.867
3.49948
[[776   0]
 [133  91]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       776
   troubled       1.00      0.41      0.58       224

avg / total       0.89      0.87      0.84      1000



8 Train accuracy: 0.868
3.33258
[[776   0]
 [132  92]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       776
   troubled       1.00      0.41      0.58       224

avg / total       0.89      0.87      0.85      1000

9 Train accuracy: 0.868
3.1688
[[776   0]
 [132  92]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       776
   troubled       1.00      0.41      0.58       224

avg / total       0.89      0.87      0.85      1000

10 Train accuracy: 0.868
3.22825
[[776   0]
 [132  92]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       776
   troubled       1.00      0.41      0.58       224

avg / total       0.89      0.87      0.85      1000



11 Train accuracy: 0.878
3.06236
[[776   0]
 [122 102]]
             precision    recall  f1-score   support

         ok       0.86      1.00      0.93       776
   troubled       1.00      0.46      0.63       224

avg / total       0.89      0.88      0.86      1000

12 Train accuracy: 0.878
3.05842
[[776   0]
 [122 102]]
             precision    recall  f1-score   support

         ok       0.86      1.00      0.93       776
   troubled       1.00      0.46      0.63       224

avg / total       0.89      0.88      0.86      1000

13 Train accuracy: 0.883
2.96118
[[776   0]
 [117 107]]
             precision    recall  f1-score   support

         ok       0.87      1.00      0.93       776
   troubled       1.00      0.48      0.65       224

avg / total       0.90      0.88      0.87      1000



14 Train accuracy: 0.885
2.91054
[[776   0]
 [115 109]]
             precision    recall  f1-score   support

         ok       0.87      1.00      0.93       776
   troubled       1.00      0.49      0.65       224

avg / total       0.90      0.89      0.87      1000

15 Train accuracy: 0.892
2.78367
[[776   0]
 [108 116]]
             precision    recall  f1-score   support

         ok       0.88      1.00      0.93       776
   troubled       1.00      0.52      0.68       224

avg / total       0.91      0.89      0.88      1000

16 Train accuracy: 0.897
2.63098
[[776   0]
 [103 121]]
             precision    recall  f1-score   support

         ok       0.88      1.00      0.94       776
   troubled       1.00      0.54      0.70       224

avg / total       0.91      0.90      0.88      1000



17 Train accuracy: 0.91
2.37216
[[776   0]
 [ 90 134]]
             precision    recall  f1-score   support

         ok       0.90      1.00      0.95       776
   troubled       1.00      0.60      0.75       224

avg / total       0.92      0.91      0.90      1000

18 Train accuracy: 0.91
2.35139
[[776   0]
 [ 90 134]]
             precision    recall  f1-score   support

         ok       0.90      1.00      0.95       776
   troubled       1.00      0.60      0.75       224

avg / total       0.92      0.91      0.90      1000

19 Train accuracy: 0.924
1.71045
[[776   0]
 [ 76 148]]
             precision    recall  f1-score   support

         ok       0.91      1.00      0.95       776
   troubled       1.00      0.66      0.80       224

avg / total       0.93      0.92      0.92      1000



20 Train accuracy: 0.886
2.91571
[[776   0]
 [114 110]]
             precision    recall  f1-score   support

         ok       0.87      1.00      0.93       776
   troubled       1.00      0.49      0.66       224

avg / total       0.90      0.89      0.87      1000

21 Train accuracy: 0.179
3.12331
[[  0 776]
 [ 45 179]]
             precision    recall  f1-score   support

         ok       0.00      0.00      0.00       776
   troubled       0.19      0.80      0.30       224

avg / total       0.04      0.18      0.07      1000

22 Train accuracy: 0.871
3.40806
[[776   0]
 [129  95]]
             precision    recall  f1-score   support

         ok       0.86      1.00      0.92       776
   troubled       1.00      0.42      0.60       224

avg / total       0.89      0.87      0.85      1000



23 Train accuracy: 0.884
2.94106
[[776   0]
 [116 108]]
             precision    recall  f1-score   support

         ok       0.87      1.00      0.93       776
   troubled       1.00      0.48      0.65       224

avg / total       0.90      0.88      0.87      1000

24 Train accuracy: 0.955
1.18609
[[776   0]
 [ 45 179]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.80      0.89       224

avg / total       0.96      0.95      0.95      1000

25 Train accuracy: 0.955
1.10846
[[776   0]
 [ 45 179]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.80      0.89       224

avg / total       0.96      0.95      0.95      1000



26 Train accuracy: 0.956
1.0561
[[776   0]
 [ 44 180]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.80      0.89       224

avg / total       0.96      0.96      0.95      1000

27 Train accuracy: 0.956
0.971642
[[776   0]
 [ 44 180]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.80      0.89       224

avg / total       0.96      0.96      0.95      1000

28 Train accuracy: 0.956
0.878584
[[776   0]
 [ 44 180]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.80      0.89       224

avg / total       0.96      0.96      0.95      1000



29 Train accuracy: 0.956
0.990622
[[776   0]
 [ 44 180]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.80      0.89       224

avg / total       0.96      0.96      0.95      1000

30 Train accuracy: 0.904
1.79946
[[776   0]
 [ 96 128]]
             precision    recall  f1-score   support

         ok       0.89      1.00      0.94       776
   troubled       1.00      0.57      0.73       224

avg / total       0.91      0.90      0.89      1000

31 Train accuracy: 0.934
0.870133
[[776   0]
 [ 66 158]]
             precision    recall  f1-score   support

         ok       0.92      1.00      0.96       776
   troubled       1.00      0.71      0.83       224

avg / total       0.94      0.93      0.93      1000



32 Train accuracy: 0.924
0.890159
[[776   0]
 [ 76 148]]
             precision    recall  f1-score   support

         ok       0.91      1.00      0.95       776
   troubled       1.00      0.66      0.80       224

avg / total       0.93      0.92      0.92      1000

33 Train accuracy: 0.886
2.28091
[[776   0]
 [114 110]]
             precision    recall  f1-score   support

         ok       0.87      1.00      0.93       776
   troubled       1.00      0.49      0.66       224

avg / total       0.90      0.89      0.87      1000

34 Train accuracy: 0.872
3.02159
[[776   0]
 [128  96]]
             precision    recall  f1-score   support

         ok       0.86      1.00      0.92       776
   troubled       1.00      0.43      0.60       224

avg / total       0.89      0.87      0.85      1000



35 Train accuracy: 0.958
0.324869
[[776   0]
 [ 42 182]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.81      0.90       224

avg / total       0.96      0.96      0.96      1000

36 Train accuracy: 0.958
0.271443
[[776   0]
 [ 42 182]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.81      0.90       224

avg / total       0.96      0.96      0.96      1000

37 Train accuracy: 0.953
0.312197
[[776   0]
 [ 47 177]]
             precision    recall  f1-score   support

         ok       0.94      1.00      0.97       776
   troubled       1.00      0.79      0.88       224

avg / total       0.96      0.95      0.95      1000



38 Train accuracy: 0.949
0.29612
[[776   0]
 [ 51 173]]
             precision    recall  f1-score   support

         ok       0.94      1.00      0.97       776
   troubled       1.00      0.77      0.87       224

avg / total       0.95      0.95      0.95      1000

39 Train accuracy: 0.863
3.72581
[[776   0]
 [137  87]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       776
   troubled       1.00      0.39      0.56       224

avg / total       0.88      0.86      0.84      1000

40 Train accuracy: 1.0
0.19144
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



41 Train accuracy: 0.955
0.109645
[[776   0]
 [ 45 179]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       776
   troubled       1.00      0.80      0.89       224

avg / total       0.96      0.95      0.95      1000

42 Train accuracy: 1.0
0.017172
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

43 Train accuracy: 1.0
0.0194433
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



44 Train accuracy: 1.0
0.0146619
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

45 Train accuracy: 1.0
0.0127665
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

46 Train accuracy: 1.0
0.0119356
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



47 Train accuracy: 1.0
0.0114036
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

48 Train accuracy: 1.0
0.0109893
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

49 Train accuracy: 1.0
0.0106336
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



50 Train accuracy: 1.0
0.0103027
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

51 Train accuracy: 1.0
0.00997372
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

52 Train accuracy: 1.0
0.00965496
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



53 Train accuracy: 1.0
0.00934614
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

54 Train accuracy: 1.0
0.00905427
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

55 Train accuracy: 1.0
0.0087881
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



56 Train accuracy: 1.0
0.00854725
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

57 Train accuracy: 1.0
0.00833005
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

58 Train accuracy: 1.0
0.00813412
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



59 Train accuracy: 1.0
0.00795363
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

60 Train accuracy: 1.0
0.00779141
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

61 Train accuracy: 1.0
0.00763917
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



62 Train accuracy: 1.0
0.0074956
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

63 Train accuracy: 1.0
0.0073638
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

64 Train accuracy: 1.0
0.00723669
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



65 Train accuracy: 1.0
0.007118
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

66 Train accuracy: 1.0
0.00700494
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

67 Train accuracy: 1.0
0.00689528
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



68 Train accuracy: 1.0
0.00677445
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

69 Train accuracy: 1.0
0.00665112
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

70 Train accuracy: 1.0
0.00653018
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



71 Train accuracy: 1.0
0.00641083
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

72 Train accuracy: 1.0
0.00629711
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

73 Train accuracy: 1.0
0.0061872
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



74 Train accuracy: 1.0
0.00608185
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

75 Train accuracy: 1.0
0.00597834
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

76 Train accuracy: 1.0
0.00587884
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



77 Train accuracy: 1.0
0.00578162
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

78 Train accuracy: 1.0
0.00568924
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

79 Train accuracy: 1.0
0.00559857
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



80 Train accuracy: 1.0
0.00551062
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

81 Train accuracy: 1.0
0.00542527
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

82 Train accuracy: 1.0
0.00534218
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



83 Train accuracy: 1.0
0.00526163
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

84 Train accuracy: 1.0
0.00518299
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

85 Train accuracy: 1.0
0.00510604
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



86 Train accuracy: 1.0
0.00503089
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

87 Train accuracy: 1.0
0.00495793
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

88 Train accuracy: 1.0
0.00488637
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



89 Train accuracy: 1.0
0.00481696
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

90 Train accuracy: 1.0
0.00474887
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

91 Train accuracy: 1.0
0.00468215
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



92 Train accuracy: 1.0
0.00461738
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

93 Train accuracy: 1.0
0.00455308
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

94 Train accuracy: 1.0
0.00449156
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



95 Train accuracy: 1.0
0.00442987
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

96 Train accuracy: 1.0
0.00437049
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

97 Train accuracy: 1.0
0.00431163
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000



98 Train accuracy: 1.0
0.004255
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

99 Train accuracy: 1.0
0.00419869
[[776   0]
 [  0 224]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       776
   troubled       1.00      1.00      1.00       224

avg / total       1.00      1.00      1.00      1000

