Generate, load and prepare policy histories

In [1]:
import os
from datetime import datetime
import support_functions as sf


PROJECT_ROOT_DIR = "/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife"
DATASETS_DIR = os.path.join(PROJECT_ROOT_DIR, "data")
TF_LOG_DIR = os.path.join(PROJECT_ROOT_DIR, "tf_logs")
TRAINING_SET_DATA_FILE = "troubled_life_policy_train_data.csv"
TEST_SET_DATA_FILE = "troubled_life_policy_test_data.csv"

now = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
log_dir = "{}/run-{}/".format(TF_LOG_DIR, now)

In [2]:
#sf.generate_troubled_life_policy_data(no_of_policies=10000, runtime=5, file_path=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))

#sf.generate_troubled_life_policy_data(no_of_policies=2000, runtime=5, file_path=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

policy_histories_train = \
    sf.load_troubled_life_policy_data(file_path=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))

policy_histories_test = \
    sf.load_troubled_life_policy_data(file_path=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

policy_histories_length_train, max_policy_history_length_train = \
    sf.get_policy_history_lengths(policy_histories=policy_histories_train)

policy_histories_length_test, max_policy_history_length_test = \
    sf.get_policy_history_lengths(policy_histories=policy_histories_test)

max_policy_history_length = max(max_policy_history_length_train, max_policy_history_length_test)

In [3]:
# Pad the histories up to maximum length of both, train and test set

# policy_histories_train = \
#     sf.pad_troubled_life_policy_histories(policy_histories=policy_histories_train,
#                                           policy_histories_lengths=policy_histories_length_train,
#                                           max_policy_history_length=max_policy_history_length)

# policy_histories_test = \
#     sf.pad_troubled_life_policy_histories(policy_histories=policy_histories_test,
#                                           policy_histories_lengths=policy_histories_length_test,
#                                           max_policy_history_length=max_policy_history_length)

# Save padded data, since always generating and padding takes too long
#policy_histories_train.to_csv(path_or_buf=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))
#policy_histories_test.to_csv(path_or_buf=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

Prepare labels and features

In [4]:
# Extract features and labels from dataset as numpy.ndarray(s)
train_labels, train_features, train_seq_lengths =\
    sf.prepare_labels_features_lengths(policy_histories=policy_histories_train,
                                       policy_histories_lengths=policy_histories_length_train, 
                                       max_policy_history_length=max_policy_history_length)
test_labels, test_features, test_seq_lengths =\
    sf.prepare_labels_features_lengths(policy_histories=policy_histories_test,
                                       policy_histories_lengths=policy_histories_length_test, 
                                       max_policy_history_length=max_policy_history_length)


Build TensorFlow graph with RNN

In [5]:
import tensorflow as tf

tf.reset_default_graph()
tf.set_random_seed(42)

# Our hyperparameters
n_steps = max_policy_history_length
n_inputs = 2
n_layers = 3
n_neurons = 100
n_outputs = 2
learning_rate = 0.0001

# Placeholders for our input sequences
seq_length = tf.placeholder(tf.int32, [None], name="seq_length")
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs], name="X")
y = tf.placeholder(tf.int32, [None], name="y")

layers = [tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,
                                      activation=tf.nn.relu)
          for layer in range(n_layers)]
multi_layer_cell = tf.contrib.rnn.MultiRNNCell(layers, state_is_tuple=False)
outputs, states = tf.nn.dynamic_rnn(multi_layer_cell, X, dtype=tf.float32)

# We feed all layers' states (after the last timestep) into a fully connected layer of 2 neurons
# (1 per class, troubled or not). Softmax layer is next
logits = tf.layers.dense(states, n_outputs)
y_pred = tf.argmax(tf.nn.softmax(logits), axis=1)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)

# Loss function and Adam Optimizer
loss = tf.reduce_mean(tf.cast(xentropy, tf.float32))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

correct = tf.nn.in_top_k(logits, y, 1)
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

init = tf.global_variables_initializer()

accuracy_summary = tf.summary.scalar('Accuracy', accuracy)
loss_summary = tf.summary.scalar('Loss', loss)

file_writer = tf.summary.FileWriter(log_dir, tf.get_default_graph())

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

n_epochs = 100
batch_size = 200

train_data = sf.TrainDataSet(train_labels=train_labels, train_features=train_features, train_seq_lengths=train_seq_lengths)

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for i in range(train_data.num_examples // batch_size):
            y_batch, X_batch, seq_length_batch = train_data.next_batch(batch_size)
            
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})

        y_train_pred = y_pred.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        y_test_pred = y_pred.eval(feed_dict={X: test_features, y: test_labels, seq_length: test_seq_lengths})
        acc_train = accuracy.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        acc_test = accuracy.eval(feed_dict={X: test_features, y: test_labels, seq_length: test_seq_lengths})

        print(epoch, "Train accuracy:", acc_train, "Test accuracy:", acc_test)
        print(confusion_matrix(y_batch, y_train_pred))
        print(classification_report(y_batch, y_train_pred, target_names=['ok', 'troubled']))

        loss_summary_str = loss_summary.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        accuracy_summary_str = accuracy_summary.eval(feed_dict={X: test_features, y: test_labels, seq_length: test_seq_lengths})
        file_writer.add_summary(loss_summary_str, epoch)
        file_writer.add_summary(accuracy_summary_str, epoch)

file_writer.close()

0 Train accuracy: 0.45 Test accuracy: 0.4445
[[51 92]
 [18 39]]
             precision    recall  f1-score   support

         ok       0.74      0.36      0.48       143
   troubled       0.30      0.68      0.41        57

avg / total       0.61      0.45      0.46       200



1 Train accuracy: 0.95 Test accuracy: 0.951
[[146   1]
 [  9  44]]
             precision    recall  f1-score   support

         ok       0.94      0.99      0.97       147
   troubled       0.98      0.83      0.90        53

avg / total       0.95      0.95      0.95       200



2 Train accuracy: 0.93 Test accuracy: 0.933
[[149   0]
 [ 14  37]]
             precision    recall  f1-score   support

         ok       0.91      1.00      0.96       149
   troubled       1.00      0.73      0.84        51

avg / total       0.94      0.93      0.93       200



3 Train accuracy: 0.96 Test accuracy: 0.9685
[[153   0]
 [  8  39]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       153
   troubled       1.00      0.83      0.91        47

avg / total       0.96      0.96      0.96       200



4 Train accuracy: 0.945 Test accuracy: 0.926
[[154   3]
 [  8  35]]
             precision    recall  f1-score   support

         ok       0.95      0.98      0.97       157
   troubled       0.92      0.81      0.86        43

avg / total       0.94      0.94      0.94       200



5 Train accuracy: 0.985 Test accuracy: 0.963
[[150   1]
 [  2  47]]
             precision    recall  f1-score   support

         ok       0.99      0.99      0.99       151
   troubled       0.98      0.96      0.97        49

avg / total       0.98      0.98      0.98       200



6 Train accuracy: 0.975 Test accuracy: 0.9685
[[145   0]
 [  5  50]]
             precision    recall  f1-score   support

         ok       0.97      1.00      0.98       145
   troubled       1.00      0.91      0.95        55

avg / total       0.98      0.97      0.97       200



7 Train accuracy: 0.985 Test accuracy: 0.969
[[159   0]
 [  3  38]]
             precision    recall  f1-score   support

         ok       0.98      1.00      0.99       159
   troubled       1.00      0.93      0.96        41

avg / total       0.99      0.98      0.98       200



8 Train accuracy: 0.965 Test accuracy: 0.9815
[[150   3]
 [  4  43]]
             precision    recall  f1-score   support

         ok       0.97      0.98      0.98       153
   troubled       0.93      0.91      0.92        47

avg / total       0.96      0.96      0.96       200



9 Train accuracy: 0.98 Test accuracy: 0.9905
[[162   1]
 [  3  34]]
             precision    recall  f1-score   support

         ok       0.98      0.99      0.99       163
   troubled       0.97      0.92      0.94        37

avg / total       0.98      0.98      0.98       200



10 Train accuracy: 0.98 Test accuracy: 0.984
[[154   0]
 [  4  42]]
             precision    recall  f1-score   support

         ok       0.97      1.00      0.99       154
   troubled       1.00      0.91      0.95        46

avg / total       0.98      0.98      0.98       200



11 Train accuracy: 0.965 Test accuracy: 0.969
[[157   0]
 [  7  36]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       157
   troubled       1.00      0.84      0.91        43

avg / total       0.97      0.96      0.96       200



12 Train accuracy: 0.985 Test accuracy: 0.9895
[[153   0]
 [  3  44]]
             precision    recall  f1-score   support

         ok       0.98      1.00      0.99       153
   troubled       1.00      0.94      0.97        47

avg / total       0.99      0.98      0.98       200



13 Train accuracy: 0.97 Test accuracy: 0.964
[[151   0]
 [  6  43]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       151
   troubled       1.00      0.88      0.93        49

avg / total       0.97      0.97      0.97       200



14 Train accuracy: 1.0 Test accuracy: 0.9915
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



15 Train accuracy: 0.975 Test accuracy: 0.974
[[156   1]
 [  4  39]]
             precision    recall  f1-score   support

         ok       0.97      0.99      0.98       157
   troubled       0.97      0.91      0.94        43

avg / total       0.97      0.97      0.97       200



16 Train accuracy: 0.84 Test accuracy: 0.848
[[145   0]
 [ 32  23]]
             precision    recall  f1-score   support

         ok       0.82      1.00      0.90       145
   troubled       1.00      0.42      0.59        55

avg / total       0.87      0.84      0.82       200



17 Train accuracy: 0.935 Test accuracy: 0.949
[[143   2]
 [ 11  44]]
             precision    recall  f1-score   support

         ok       0.93      0.99      0.96       145
   troubled       0.96      0.80      0.87        55

avg / total       0.94      0.94      0.93       200



18 Train accuracy: 0.97 Test accuracy: 0.9715
[[152   2]
 [  4  42]]
             precision    recall  f1-score   support

         ok       0.97      0.99      0.98       154
   troubled       0.95      0.91      0.93        46

avg / total       0.97      0.97      0.97       200



19 Train accuracy: 0.98 Test accuracy: 0.973
[[150   3]
 [  1  46]]
             precision    recall  f1-score   support

         ok       0.99      0.98      0.99       153
   troubled       0.94      0.98      0.96        47

avg / total       0.98      0.98      0.98       200



20 Train accuracy: 0.97 Test accuracy: 0.979
[[150   0]
 [  6  44]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       150
   troubled       1.00      0.88      0.94        50

avg / total       0.97      0.97      0.97       200



21 Train accuracy: 0.975 Test accuracy: 0.9895
[[149   1]
 [  4  46]]
             precision    recall  f1-score   support

         ok       0.97      0.99      0.98       150
   troubled       0.98      0.92      0.95        50

avg / total       0.98      0.97      0.97       200



22 Train accuracy: 0.995 Test accuracy: 0.9945
[[155   0]
 [  1  44]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       155
   troubled       1.00      0.98      0.99        45

avg / total       1.00      0.99      0.99       200



23 Train accuracy: 0.985 Test accuracy: 0.9895
[[164   1]
 [  2  33]]
             precision    recall  f1-score   support

         ok       0.99      0.99      0.99       165
   troubled       0.97      0.94      0.96        35

avg / total       0.98      0.98      0.98       200



24 Train accuracy: 0.99 Test accuracy: 0.9845
[[150   0]
 [  2  48]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       150
   troubled       1.00      0.96      0.98        50

avg / total       0.99      0.99      0.99       200



25 Train accuracy: 1.0 Test accuracy: 0.982
[[149   0]
 [  0  51]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       149
   troubled       1.00      1.00      1.00        51

avg / total       1.00      1.00      1.00       200



26 Train accuracy: 0.545 Test accuracy: 0.5145
[[65 89]
 [ 2 44]]
             precision    recall  f1-score   support

         ok       0.97      0.42      0.59       154
   troubled       0.33      0.96      0.49        46

avg / total       0.82      0.55      0.57       200



27 Train accuracy: 0.995 Test accuracy: 0.99
[[147   1]
 [  0  52]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       148
   troubled       0.98      1.00      0.99        52

avg / total       1.00      0.99      1.00       200



28 Train accuracy: 1.0 Test accuracy: 0.9945
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



29 Train accuracy: 1.0 Test accuracy: 0.9985
[[148   0]
 [  0  52]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       148
   troubled       1.00      1.00      1.00        52

avg / total       1.00      1.00      1.00       200



30 Train accuracy: 1.0 Test accuracy: 0.996
[[153   0]
 [  0  47]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       153
   troubled       1.00      1.00      1.00        47

avg / total       1.00      1.00      1.00       200



31 Train accuracy: 0.995 Test accuracy: 0.9975
[[151   0]
 [  1  48]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       151
   troubled       1.00      0.98      0.99        49

avg / total       1.00      0.99      0.99       200



32 Train accuracy: 1.0 Test accuracy: 0.9965
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



33 Train accuracy: 1.0 Test accuracy: 0.996
[[153   0]
 [  0  47]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       153
   troubled       1.00      1.00      1.00        47

avg / total       1.00      1.00      1.00       200



34 Train accuracy: 1.0 Test accuracy: 0.9965
[[152   0]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       152
   troubled       1.00      1.00      1.00        48

avg / total       1.00      1.00      1.00       200



35 Train accuracy: 1.0 Test accuracy: 0.9985
[[158   0]
 [  0  42]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       158
   troubled       1.00      1.00      1.00        42

avg / total       1.00      1.00      1.00       200



36 Train accuracy: 0.995 Test accuracy: 0.998
[[164   1]
 [  0  35]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       165
   troubled       0.97      1.00      0.99        35

avg / total       1.00      0.99      1.00       200



37 Train accuracy: 1.0 Test accuracy: 0.9985
[[152   0]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       152
   troubled       1.00      1.00      1.00        48

avg / total       1.00      1.00      1.00       200



38 Train accuracy: 0.995 Test accuracy: 0.9985
[[151   0]
 [  1  48]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       151
   troubled       1.00      0.98      0.99        49

avg / total       1.00      0.99      0.99       200



39 Train accuracy: 1.0 Test accuracy: 0.999
[[148   0]
 [  0  52]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       148
   troubled       1.00      1.00      1.00        52

avg / total       1.00      1.00      1.00       200



40 Train accuracy: 1.0 Test accuracy: 0.998
[[156   0]
 [  0  44]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       156
   troubled       1.00      1.00      1.00        44

avg / total       1.00      1.00      1.00       200



41 Train accuracy: 0.995 Test accuracy: 0.996
[[154   1]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       155
   troubled       0.98      1.00      0.99        45

avg / total       1.00      0.99      1.00       200



42 Train accuracy: 0.995 Test accuracy: 0.9985
[[158   0]
 [  1  41]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       158
   troubled       1.00      0.98      0.99        42

avg / total       1.00      0.99      0.99       200



43 Train accuracy: 0.97 Test accuracy: 0.97
[[128   6]
 [  0  66]]
             precision    recall  f1-score   support

         ok       1.00      0.96      0.98       134
   troubled       0.92      1.00      0.96        66

avg / total       0.97      0.97      0.97       200



44 Train accuracy: 1.0 Test accuracy: 0.9935
[[157   0]
 [  0  43]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       157
   troubled       1.00      1.00      1.00        43

avg / total       1.00      1.00      1.00       200



45 Train accuracy: 0.99 Test accuracy: 0.9885
[[147   1]
 [  1  51]]
             precision    recall  f1-score   support

         ok       0.99      0.99      0.99       148
   troubled       0.98      0.98      0.98        52

avg / total       0.99      0.99      0.99       200



46 Train accuracy: 0.995 Test accuracy: 0.997
[[149   0]
 [  1  50]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       149
   troubled       1.00      0.98      0.99        51

avg / total       1.00      0.99      0.99       200



47 Train accuracy: 1.0 Test accuracy: 0.9985
[[152   0]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       152
   troubled       1.00      1.00      1.00        48

avg / total       1.00      1.00      1.00       200



48 Train accuracy: 1.0 Test accuracy: 0.9985
[[160   0]
 [  0  40]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       160
   troubled       1.00      1.00      1.00        40

avg / total       1.00      1.00      1.00       200



49 Train accuracy: 1.0 Test accuracy: 0.9975
[[161   0]
 [  0  39]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       161
   troubled       1.00      1.00      1.00        39

avg / total       1.00      1.00      1.00       200



50 Train accuracy: 1.0 Test accuracy: 0.9985
[[158   0]
 [  0  42]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       158
   troubled       1.00      1.00      1.00        42

avg / total       1.00      1.00      1.00       200



51 Train accuracy: 0.99 Test accuracy: 0.994
[[148   2]
 [  0  50]]
             precision    recall  f1-score   support

         ok       1.00      0.99      0.99       150
   troubled       0.96      1.00      0.98        50

avg / total       0.99      0.99      0.99       200



52 Train accuracy: 0.99 Test accuracy: 0.999
[[148   0]
 [  2  50]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       148
   troubled       1.00      0.96      0.98        52

avg / total       0.99      0.99      0.99       200



53 Train accuracy: 0.995 Test accuracy: 0.9945
[[152   0]
 [  1  47]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       152
   troubled       1.00      0.98      0.99        48

avg / total       1.00      0.99      0.99       200



54 Train accuracy: 1.0 Test accuracy: 0.999
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



55 Train accuracy: 1.0 Test accuracy: 0.999
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



56 Train accuracy: 0.815 Test accuracy: 0.7985
[[159   0]
 [ 37   4]]
             precision    recall  f1-score   support

         ok       0.81      1.00      0.90       159
   troubled       1.00      0.10      0.18        41

avg / total       0.85      0.81      0.75       200



57 Train accuracy: 1.0 Test accuracy: 0.9865
[[153   0]
 [  0  47]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       153
   troubled       1.00      1.00      1.00        47

avg / total       1.00      1.00      1.00       200



58 Train accuracy: 0.995 Test accuracy: 0.9975
[[144   0]
 [  1  55]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       144
   troubled       1.00      0.98      0.99        56

avg / total       1.00      0.99      0.99       200



59 Train accuracy: 1.0 Test accuracy: 0.998
[[161   0]
 [  0  39]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       161
   troubled       1.00      1.00      1.00        39

avg / total       1.00      1.00      1.00       200



60 Train accuracy: 1.0 Test accuracy: 0.9985
[[158   0]
 [  0  42]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       158
   troubled       1.00      1.00      1.00        42

avg / total       1.00      1.00      1.00       200



61 Train accuracy: 1.0 Test accuracy: 0.9935
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



62 Train accuracy: 0.995 Test accuracy: 0.996
[[148   1]
 [  0  51]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       149
   troubled       0.98      1.00      0.99        51

avg / total       1.00      0.99      1.00       200



63 Train accuracy: 1.0 Test accuracy: 0.9985
[[149   0]
 [  0  51]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       149
   troubled       1.00      1.00      1.00        51

avg / total       1.00      1.00      1.00       200



64 Train accuracy: 1.0 Test accuracy: 0.9965
[[152   0]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       152
   troubled       1.00      1.00      1.00        48

avg / total       1.00      1.00      1.00       200



65 Train accuracy: 0.99 Test accuracy: 0.997
[[160   0]
 [  2  38]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       160
   troubled       1.00      0.95      0.97        40

avg / total       0.99      0.99      0.99       200



66 Train accuracy: 1.0 Test accuracy: 0.9995
[[158   0]
 [  0  42]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       158
   troubled       1.00      1.00      1.00        42

avg / total       1.00      1.00      1.00       200



67 Train accuracy: 1.0 Test accuracy: 0.9995
[[169   0]
 [  0  31]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       169
   troubled       1.00      1.00      1.00        31

avg / total       1.00      1.00      1.00       200



68 Train accuracy: 1.0 Test accuracy: 0.999
[[153   0]
 [  0  47]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       153
   troubled       1.00      1.00      1.00        47

avg / total       1.00      1.00      1.00       200



69 Train accuracy: 1.0 Test accuracy: 0.9985
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



70 Train accuracy: 1.0 Test accuracy: 0.999
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



71 Train accuracy: 1.0 Test accuracy: 0.999
[[150   0]
 [  0  50]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       150
   troubled       1.00      1.00      1.00        50

avg / total       1.00      1.00      1.00       200



72 Train accuracy: 1.0 Test accuracy: 0.9965
[[153   0]
 [  0  47]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       153
   troubled       1.00      1.00      1.00        47

avg / total       1.00      1.00      1.00       200



73 Train accuracy: 1.0 Test accuracy: 0.9985
[[145   0]
 [  0  55]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       145
   troubled       1.00      1.00      1.00        55

avg / total       1.00      1.00      1.00       200



74 Train accuracy: 1.0 Test accuracy: 0.9995
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



75 Train accuracy: 1.0 Test accuracy: 0.999
[[159   0]
 [  0  41]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       159
   troubled       1.00      1.00      1.00        41

avg / total       1.00      1.00      1.00       200



76 Train accuracy: 1.0 Test accuracy: 0.9995
[[153   0]
 [  0  47]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       153
   troubled       1.00      1.00      1.00        47

avg / total       1.00      1.00      1.00       200



77 Train accuracy: 1.0 Test accuracy: 0.9975
[[153   0]
 [  0  47]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       153
   troubled       1.00      1.00      1.00        47

avg / total       1.00      1.00      1.00       200



78 Train accuracy: 0.77 Test accuracy: 0.8
[[115  44]
 [  2  39]]
             precision    recall  f1-score   support

         ok       0.98      0.72      0.83       159
   troubled       0.47      0.95      0.63        41

avg / total       0.88      0.77      0.79       200



79 Train accuracy: 1.0 Test accuracy: 0.9935
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



80 Train accuracy: 0.945 Test accuracy: 0.9375
[[158   0]
 [ 11  31]]
             precision    recall  f1-score   support

         ok       0.93      1.00      0.97       158
   troubled       1.00      0.74      0.85        42

avg / total       0.95      0.94      0.94       200



81 Train accuracy: 1.0 Test accuracy: 0.9945
[[155   0]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       155
   troubled       1.00      1.00      1.00        45

avg / total       1.00      1.00      1.00       200



82 Train accuracy: 0.99 Test accuracy: 0.9965
[[151   2]
 [  0  47]]
             precision    recall  f1-score   support

         ok       1.00      0.99      0.99       153
   troubled       0.96      1.00      0.98        47

avg / total       0.99      0.99      0.99       200



83 Train accuracy: 0.995 Test accuracy: 0.999
[[162   0]
 [  1  37]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       162
   troubled       1.00      0.97      0.99        38

avg / total       1.00      0.99      0.99       200



84 Train accuracy: 1.0 Test accuracy: 0.9975
[[157   0]
 [  0  43]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       157
   troubled       1.00      1.00      1.00        43

avg / total       1.00      1.00      1.00       200



85 Train accuracy: 1.0 Test accuracy: 0.9985
[[155   0]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       155
   troubled       1.00      1.00      1.00        45

avg / total       1.00      1.00      1.00       200



86 Train accuracy: 1.0 Test accuracy: 0.9995
[[150   0]
 [  0  50]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       150
   troubled       1.00      1.00      1.00        50

avg / total       1.00      1.00      1.00       200



87 Train accuracy: 1.0 Test accuracy: 0.9985
[[162   0]
 [  0  38]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       162
   troubled       1.00      1.00      1.00        38

avg / total       1.00      1.00      1.00       200



88 Train accuracy: 1.0 Test accuracy: 0.9995
[[149   0]
 [  0  51]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       149
   troubled       1.00      1.00      1.00        51

avg / total       1.00      1.00      1.00       200



89 Train accuracy: 1.0 Test accuracy: 0.996
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



90 Train accuracy: 1.0 Test accuracy: 0.9995
[[145   0]
 [  0  55]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       145
   troubled       1.00      1.00      1.00        55

avg / total       1.00      1.00      1.00       200



91 Train accuracy: 0.995 Test accuracy: 0.998
[[154   1]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       155
   troubled       0.98      1.00      0.99        45

avg / total       1.00      0.99      1.00       200



92 Train accuracy: 1.0 Test accuracy: 0.997
[[159   0]
 [  0  41]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       159
   troubled       1.00      1.00      1.00        41

avg / total       1.00      1.00      1.00       200



93 Train accuracy: 1.0 Test accuracy: 0.9995
[[156   0]
 [  0  44]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       156
   troubled       1.00      1.00      1.00        44

avg / total       1.00      1.00      1.00       200



94 Train accuracy: 1.0 Test accuracy: 0.997
[[142   0]
 [  0  58]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       142
   troubled       1.00      1.00      1.00        58

avg / total       1.00      1.00      1.00       200



95 Train accuracy: 1.0 Test accuracy: 0.9985
[[155   0]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       155
   troubled       1.00      1.00      1.00        45

avg / total       1.00      1.00      1.00       200



96 Train accuracy: 1.0 Test accuracy: 0.9995
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



97 Train accuracy: 1.0 Test accuracy: 0.9995
[[149   0]
 [  0  51]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       149
   troubled       1.00      1.00      1.00        51

avg / total       1.00      1.00      1.00       200



98 Train accuracy: 1.0 Test accuracy: 0.999
[[162   0]
 [  0  38]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       162
   troubled       1.00      1.00      1.00        38

avg / total       1.00      1.00      1.00       200



99 Train accuracy: 1.0 Test accuracy: 0.999
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200

