In [1]:
import os
from datetime import datetime

PROJECT_ROOT_DIR = "/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife"
DATASETS_DIR = os.path.join(PROJECT_ROOT_DIR, "data")
TF_LOG_DIR = os.path.join(PROJECT_ROOT_DIR, "tf_logs")
MODEL_CHECKPOINTS_DIR = os.path.join(PROJECT_ROOT_DIR, "model_checkpoints")
TRAINING_SET_DATA_FILE = "troubled_life_policy_train_data.csv"
TEST_SET_DATA_FILE = "troubled_life_policy_test_data.csv"

now = datetime.now().strftime("%Y%m%d-%H%M%S")
log_dir = "{}/run-{}/".format(TF_LOG_DIR, now)


import data_preparation as dp

#dp.generate_troubled_life_policy_data(no_of_policies=10000, runtime=5, file_path=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))

#dp.generate_troubled_life_policy_data(no_of_policies=2000, runtime=5, file_path=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

policy_histories_train = \
    dp.load_troubled_life_policy_data(file_path=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))

policy_histories_test = \
    dp.load_troubled_life_policy_data(file_path=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

policy_histories_length_train, max_policy_history_length_train = \
    dp.get_policy_history_lengths(policy_histories=policy_histories_train)

policy_histories_length_test, max_policy_history_length_test = \
    dp.get_policy_history_lengths(policy_histories=policy_histories_test)

max_policy_history_length = max(max_policy_history_length_train, max_policy_history_length_test)



# Pad the histories up to maximum length of both, train and test set

# policy_histories_train = \
#     dp.pad_troubled_life_policy_histories(policy_histories=policy_histories_train,
#                                           policy_histories_lengths=policy_histories_length_train,
#                                           max_policy_history_length=max_policy_history_length)
# 
# policy_histories_test = \
#     dp.pad_troubled_life_policy_histories(policy_histories=policy_histories_test,
#                                           policy_histories_lengths=policy_histories_length_test,
#                                           max_policy_history_length=max_policy_history_length)
# 
# # # Save padded data, since always generating and padding takes too long
# policy_histories_train.to_csv(path_or_buf=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))
# policy_histories_test.to_csv(path_or_buf=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

# Extract features and labels from dataset as numpy.ndarray(s)
binary_classification = True

train_labels, train_features, train_seq_lengths =\
    dp.prepare_labels_features_lengths(policy_histories=policy_histories_train,
                                       policy_histories_lengths=policy_histories_length_train, 
                                       max_policy_history_length=max_policy_history_length,
                                       binary_classification=binary_classification)
test_labels, test_features, test_seq_lengths =\
    dp.prepare_labels_features_lengths(policy_histories=policy_histories_test,
                                       policy_histories_lengths=policy_histories_length_test, 
                                       max_policy_history_length=max_policy_history_length,
                                       binary_classification=binary_classification)

train_data = dp.TrainDataSet(train_labels=train_labels, train_features=train_features, train_seq_lengths=train_seq_lengths)

In [5]:
import tensorflow as tf
import gan as gan


g_learning_rate = 0.0001
d_real_learning_rate = 0.0001
d_fake_learning_rate = 0.0001
noise_dimensions = 10
batch_size = 200
g_n_outputs = 2
d_n_inputs = 2
d_n_outputs = 2 if binary_classification else max_policy_history_length

tf.reset_default_graph()
tf.set_random_seed(42)

noise = tf.placeholder(tf.float32, [batch_size, max_policy_history_length, noise_dimensions], name='noise')
noise_seq_length = tf.placeholder(tf.int32, [None], name='noise_seq_length')

X = tf.placeholder(tf.float32, [None, max_policy_history_length, d_n_inputs], name="X")
y = tf.placeholder(tf.int32, [None], name="y")
X_seq_length = tf.placeholder(tf.int32, [None], name="X_seq_length")

g_data = gan.generator(noise=noise, batch_size=batch_size, n_outputs=g_n_outputs, 
                       max_seq_length=max_policy_history_length, seq_length=noise_seq_length)

# Let's make sure the initial value at [:, 0, 1] is 0 (current capital at policy inception)
flat = tf.reshape(tensor=g_data, shape=[batch_size * max_policy_history_length * g_n_outputs])
flat2 = tf.Variable(initial_value=tf.zeros_like(flat), trainable=False, name="xyFlat")
flat3 = tf.assign(ref=flat2, value=flat)
flat4 = tf.scatter_update(flat3, [1 + i * max_policy_history_length * g_n_outputs for i in range(batch_size)],
                                 [0 for j in range(batch_size)])
g_ms_data = tf.reshape(tensor=flat4, shape=[batch_size, max_policy_history_length, g_n_outputs])

logits_d_for_X, y_pred_X = gan.discriminator(X=X, seq_length=X_seq_length, n_outputs=d_n_outputs)
logits_d_for_g, y_pred_g = gan.discriminator(X=g_ms_data, seq_length=noise_seq_length, n_outputs=d_n_outputs, reuse=True)

g_loss, accuracy_g = gan.generator_loss(batch_size=batch_size, logits_d=logits_d_for_g, logits_g = g_data)
d_loss_real, accuracy_d_real = gan.discriminator_loss_real(logits=logits_d_for_X, y=y)
d_loss_fake, accuracy_d_fake = gan.discriminator_loss_fake(batch_size=batch_size, logits=logits_d_for_g)

g_trainer = gan.generator_trainer(g_learning_rate, g_loss)
d_trainer_real = gan.discriminator_trainer_real(d_real_learning_rate, d_loss_real)
d_trainer_fake = gan.discriminator_trainer_fake(d_fake_learning_rate, d_loss_fake)

tf.summary.scalar('Generator_loss', g_loss)
tf.summary.scalar('Discriminator_loss_real', d_loss_real)
tf.summary.scalar('Discriminator_loss_fake', d_loss_fake)

merged = tf.summary.merge_all()
writer = tf.summary.FileWriter(log_dir, tf.get_default_graph())

In [6]:
import numpy as np

np.set_printoptions(formatter={'float_kind': (lambda x: "%.2f" % x)})

sess = tf.Session()

sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

saver = tf.train.Saver()

# n_epochs = 100
# 
# # Pre-train discriminator
# for epoch in range(n_epochs):
#     for batch in range(train_data.num_examples // batch_size):
#         noise_batch = np.random.normal(0, 1, size=[batch_size, max_policy_history_length, noise_dimensions])
#         noise_seq_length_batch = np.full(batch_size, max_policy_history_length)
# 
#         y_batch, X_batch, X_seq_length_batch = train_data.next_batch(batch_size)
# 
#         _, __, dLossReal, dLossFake, acc_real_train, acc_fake_train = \
#             sess.run([d_trainer_real, d_trainer_fake, d_loss_real, d_loss_fake, accuracy_d_real, accuracy_d_fake],
#                      {X: X_batch, y: y_batch, X_seq_length: X_seq_length_batch,
#                       noise: noise_batch, noise_seq_length: noise_seq_length_batch})
# 
#     print("Epoch:", epoch, "dLossReal:", dLossReal, "acc_real_train:", acc_real_train,
#           "dLossFake:", dLossFake, "acc_fake_train:", acc_fake_train)
# 
# saver.save(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "discriminator.ckpt"))

In [7]:
#saver.restore(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "discriminator.ckpt"))

#Train generator and discriminator together
n_epochs = 200

for epoch in range(n_epochs):
    for batch in range(train_data.num_examples // batch_size):
        noise_batch = np.random.normal(0, 1, size=[batch_size, max_policy_history_length, noise_dimensions])
        noise_seq_length_batch = np.full(batch_size, max_policy_history_length)
        
        # y_batch, X_batch, X_seq_length_batch = train_data.next_batch(batch_size)
        # 
        # # Train discriminator on both real and fake data
        # _, __, dLossReal, dLossFake, acc_real_train, acc_fake_train = \
        #     sess.run([d_trainer_real, d_trainer_fake, d_loss_real, d_loss_fake, accuracy_d_real, accuracy_d_fake],
        #              {X: X_batch, y: y_batch, X_seq_length: X_seq_length_batch,
        #               noise: noise_batch, noise_seq_length: noise_seq_length_batch})
        # 
        # # Train generator
        # noise_batch = np.random.normal(0, 1, size=[batch_size, max_policy_history_length, noise_dimensions])
    
        _, dLossFake, acc_d_fake, gLoss, acc_g, gData = sess.run([g_trainer, d_loss_fake, accuracy_d_fake,
                                                                         g_loss, accuracy_g, g_ms_data],
                                          feed_dict={noise: noise_batch, noise_seq_length: noise_seq_length_batch})

    print("Epoch:", epoch, 
          "dLossFake:", dLossFake, "acc_fake_train:", acc_d_fake,
          "gLoss:", gLoss, "acc_g:", acc_g)

    print(gData[0])


Epoch: 0 dLossFake: 0.6986 acc_fake_train: 0.225 gLoss: 2497.9 acc_g: 0.775
[[0.76 0.00]
 [0.94 -0.06]
 [1.12 0.04]
 [1.69 0.19]
 [1.33 0.12]
 [1.26 0.16]
 [1.37 0.17]
 [1.55 0.13]
 [1.71 0.21]
 [1.38 0.09]
 [1.48 0.09]
 [1.43 0.17]
 [1.74 0.16]
 [1.44 -0.01]
 [1.75 0.03]]


Epoch: 1 dLossFake: 0.718764 acc_fake_train: 0.165 gLoss: 2489.18 acc_g: 0.835
[[4.60 0.00]
 [5.85 0.10]
 [6.34 0.08]
 [5.87 0.22]
 [6.37 0.17]
 [6.23 0.40]
 [7.86 0.47]
 [7.76 0.31]
 [8.73 0.23]
 [8.16 0.58]
 [7.36 0.57]
 [5.82 0.79]
 [6.78 0.49]
 [6.84 0.61]
 [6.60 0.62]]


Epoch: 2 dLossFake: 0.794291 acc_fake_train: 0.12 gLoss: 2463.0 acc_g: 0.88
[[21.53 0.00]
 [21.03 0.57]
 [19.98 0.89]
 [30.12 1.05]
 [26.66 0.97]
 [27.09 1.20]
 [28.31 1.96]
 [24.69 1.57]
 [23.37 1.89]
 [27.33 1.92]
 [23.37 1.87]
 [26.18 1.58]
 [28.87 1.74]
 [27.53 1.52]
 [24.29 1.74]]


Epoch: 3 dLossFake: 1.09009 acc_fake_train: 0.025 gLoss: 2397.72 acc_g: 0.975
[[46.55 0.00]
 [57.57 0.86]
 [43.07 1.58]
 [51.68 2.28]
 [69.36 1.81]
 [76.89 2.03]
 [76.25 2.91]
 [68.07 3.35]
 [61.74 2.85]
 [65.78 3.31]
 [69.38 2.89]
 [58.11 2.20]
 [62.36 2.98]
 [68.55 2.74]
 [72.45 2.35]]


Epoch: 4 dLossFake: 1.81224 acc_fake_train: 0.025 gLoss: 2282.75 acc_g: 0.975
[[112.60 0.00]
 [110.27 1.30]
 [127.84 3.17]
 [137.65 4.34]
 [144.23 4.01]
 [118.78 4.22]
 [156.17 5.57]
 [126.01 3.38]
 [171.97 4.83]
 [157.69 4.01]
 [135.15 4.54]
 [139.03 4.97]
 [157.33 4.42]
 [147.90 3.75]
 [127.33 4.07]]


Epoch: 5 dLossFake: 3.03648 acc_fake_train: 0.025 gLoss: 2066.94 acc_g: 0.975
[[145.22 0.00]
 [145.08 1.27]
 [237.38 2.38]
 [284.94 6.11]
 [256.09 5.27]
 [260.28 7.06]
 [243.07 7.45]
 [247.91 5.97]
 [281.00 6.80]
 [282.45 6.48]
 [238.19 5.77]
 [223.93 6.96]
 [229.41 5.88]
 [235.39 4.30]
 [245.15 4.98]]


Epoch: 6 dLossFake: 5.71803 acc_fake_train: 0.02 gLoss: 1757.15 acc_g: 0.98
[[456.19 0.00]
 [376.23 2.86]
 [425.15 8.11]
 [451.34 12.76]
 [410.66 8.18]
 [416.77 9.05]
 [407.79 9.72]
 [457.41 8.64]
 [389.15 7.51]
 [456.54 9.51]
 [511.34 8.74]
 [454.77 7.14]
 [528.11 10.54]
 [505.29 8.33]
 [482.63 8.31]]


Epoch: 7 dLossFake: 9.64194 acc_fake_train: 0.005 gLoss: 1286.89 acc_g: 0.995
[[708.31 0.00]
 [784.01 4.84]
 [762.97 9.88]
 [696.68 19.92]
 [711.43 16.71]
 [656.86 12.96]
 [857.81 16.51]
 [693.02 10.33]
 [694.43 14.46]
 [911.62 16.40]
 [915.16 9.32]
 [887.01 12.76]
 [772.40 15.44]
 [764.28 12.44]
 [835.69 12.33]]


Epoch: 8 dLossFake: 15.9625 acc_fake_train: 0.0 gLoss: 629.902 acc_g: 1.0
[[696.14 0.00]
 [854.58 3.78]
 [984.46 7.65]
 [1046.64 20.69]
 [1125.83 18.45]
 [1082.29 17.07]
 [1091.37 19.33]
 [1059.14 17.13]
 [1167.03 17.35]
 [1218.38 16.98]
 [1112.97 15.19]
 [1257.04 17.87]
 [1201.64 14.08]
 [1291.40 16.23]
 [1136.64 14.99]]


Epoch: 9 dLossFake: 18.4107 acc_fake_train: 0.0 gLoss: 369.718 acc_g: 1.0
[[1395.65 0.00]
 [1100.55 2.91]
 [1014.62 19.29]
 [1590.79 30.15]
 [1717.48 16.08]
 [1490.32 18.37]
 [1463.07 31.35]
 [1306.29 22.97]
 [1530.32 20.71]
 [1380.75 16.78]
 [1428.18 20.16]
 [1599.65 21.02]
 [1560.39 15.31]
 [1784.81 20.98]
 [1607.93 17.86]]


Epoch: 10 dLossFake: 20.4845 acc_fake_train: 0.0 gLoss: 341.2 acc_g: 1.0
[[1353.67 0.00]
 [1304.53 3.88]
 [1361.67 15.48]
 [1598.28 34.71]
 [1853.39 23.93]
 [1859.38 21.79]
 [1922.50 30.35]
 [1649.61 27.43]
 [1606.74 27.06]
 [1566.64 22.60]
 [1714.45 21.08]
 [1649.80 19.08]
 [1610.08 20.38]
 [1514.75 18.91]
 [1513.37 17.05]]


Epoch: 11 dLossFake: 19.1641 acc_fake_train: 0.0 gLoss: 341.547 acc_g: 1.0
[[1433.37 0.00]
 [1318.51 4.11]
 [1483.40 17.34]
 [1743.33 36.85]
 [1602.71 20.29]
 [1562.40 24.48]
 [1529.47 27.71]
 [1467.98 21.65]
 [1695.39 22.48]
 [1719.86 21.13]
 [1705.96 20.20]
 [1653.83 21.57]
 [1513.14 19.49]
 [1513.97 18.83]
 [1719.74 19.82]]


Epoch: 12 dLossFake: 19.4693 acc_fake_train: 0.0 gLoss: 343.21 acc_g: 1.0
[[1213.92 0.00]
 [1375.19 6.26]
 [1600.68 12.40]
 [1834.98 36.05]
 [1923.87 27.24]
 [1633.53 26.06]
 [1474.77 31.51]
 [1408.14 24.46]
 [1370.98 18.85]
 [1465.71 20.50]
 [1507.20 18.55]
 [1485.48 16.27]
 [1498.67 18.32]
 [1477.68 17.90]
 [1622.95 18.69]]


Epoch: 13 dLossFake: 19.4113 acc_fake_train: 0.0 gLoss: 293.357 acc_g: 1.0
[[1352.36 0.00]
 [1180.57 3.22]
 [1456.00 16.03]
 [1429.12 30.56]
 [1674.92 24.59]
 [1572.01 21.22]
 [1542.04 25.03]
 [1309.24 22.42]
 [1223.74 21.13]
 [1289.57 19.16]
 [1343.52 15.44]
 [1563.52 16.89]
 [1787.04 18.71]
 [1691.08 16.42]
 [1756.74 22.76]]


Epoch: 14 dLossFake: 19.6915 acc_fake_train: 0.0 gLoss: 291.586 acc_g: 1.0
[[1349.46 0.00]
 [1471.96 5.83]
 [1296.17 13.86]
 [1618.27 36.46]
 [1435.49 19.01]
 [1536.44 21.69]
 [1647.02 26.00]
 [1732.40 22.88]
 [1449.08 20.82]
 [1478.01 25.55]
 [1473.37 18.88]
 [1501.07 15.43]
 [1443.95 17.84]
 [1628.59 20.62]
 [1481.09 14.15]]


Epoch: 15 dLossFake: 19.9302 acc_fake_train: 0.0 gLoss: 311.191 acc_g: 1.0
[[1245.22 0.00]
 [1407.07 5.89]
 [1407.19 13.39]
 [1512.43 32.36]
 [1786.39 28.39]
 [1703.04 20.46]
 [1638.45 27.18]
 [1632.59 26.06]
 [1734.25 23.94]
 [1782.87 23.23]
 [1660.81 22.69]
 [1475.98 21.33]
 [1619.49 21.15]
 [1719.45 18.39]
 [1880.94 19.27]]


Epoch: 16 dLossFake: 18.9785 acc_fake_train: 0.0 gLoss: 327.263 acc_g: 1.0
[[1157.69 0.00]
 [1292.15 5.16]
 [1488.79 12.40]
 [1549.14 31.44]
 [1484.07 23.73]
 [1532.75 24.32]
 [1533.99 24.09]
 [1544.46 21.06]
 [1499.30 22.71]
 [1439.17 21.56]
 [1507.24 20.58]
 [1610.34 19.26]
 [1790.32 19.01]
 [1814.68 18.94]
 [1728.07 20.63]]


Epoch: 17 dLossFake: 19.9807 acc_fake_train: 0.0 gLoss: 298.979 acc_g: 1.0
[[1116.24 0.00]
 [1249.35 5.47]
 [1290.70 11.93]
 [1427.39 30.47]
 [1524.22 22.80]
 [1437.70 20.09]
 [1644.44 26.25]
 [1480.16 19.78]
 [1476.34 23.10]
 [1788.67 26.33]
 [1584.26 14.67]
 [1623.90 21.54]
 [1594.02 21.76]
 [1870.54 21.40]
 [1732.10 17.15]]


Epoch: 18 dLossFake: 19.8971 acc_fake_train: 0.0 gLoss: 306.249 acc_g: 1.0
[[1048.93 0.00]
 [1159.37 5.06]
 [1240.40 11.81]
 [1547.82 30.90]
 [1615.24 21.32]
 [1763.30 22.42]
 [1662.39 27.25]
 [1695.31 27.01]
 [1568.12 22.72]
 [1449.29 23.10]
 [1559.59 21.61]
 [1533.74 18.16]
 [1464.40 17.14]
 [1601.16 21.07]
 [1498.20 14.97]]


Epoch: 19 dLossFake: 18.9517 acc_fake_train: 0.0 gLoss: 312.116 acc_g: 1.0
[[1080.70 0.00]
 [1090.77 3.65]
 [1260.84 12.31]
 [1421.42 29.30]
 [1623.11 22.55]
 [1663.11 20.38]
 [1683.03 25.86]
 [1615.58 25.46]
 [1957.34 28.56]
 [1761.25 19.94]
 [1713.40 25.29]
 [1648.13 23.67]
 [1576.32 19.00]
 [1430.17 17.52]
 [1476.66 19.19]]


Epoch: 20 dLossFake: 20.0313 acc_fake_train: 0.0 gLoss: 301.812 acc_g: 1.0
[[1457.68 0.00]
 [1329.30 4.54]
 [1410.40 17.15]
 [1652.30 36.64]
 [1800.26 23.41]
 [1740.62 22.39]
 [1723.06 30.25]
 [1585.14 25.47]
 [1474.62 22.60]
 [1563.72 23.01]
 [1672.84 20.28]
 [1733.22 19.18]
 [1913.72 23.30]
 [1729.51 18.83]
 [1589.47 22.35]]


Epoch: 21 dLossFake: 19.365 acc_fake_train: 0.0 gLoss: 268.635 acc_g: 1.0
[[982.82 0.00]
 [1176.68 5.25]
 [1393.75 9.75]
 [1507.84 28.64]
 [1728.46 26.42]
 [1723.04 23.17]
 [1782.87 28.81]
 [1695.55 26.51]
 [1607.08 25.17]
 [1634.28 24.44]
 [1582.65 20.88]
 [1705.62 22.81]
 [1636.99 19.59]
 [1458.35 18.83]
 [1451.67 19.36]]


Epoch: 22 dLossFake: 19.2481 acc_fake_train: 0.0 gLoss: 304.989 acc_g: 1.0
[[1111.37 0.00]
 [1151.44 4.54]
 [1410.49 11.96]
 [1696.76 32.52]
 [1628.56 20.04]
 [1537.31 25.11]
 [1737.05 29.78]
 [1542.28 20.25]
 [1905.49 27.71]
 [1642.30 21.76]
 [1579.41 23.35]
 [1691.91 24.47]
 [1544.27 16.29]
 [1455.40 18.26]
 [1725.28 23.43]]


Epoch: 23 dLossFake: 19.4241 acc_fake_train: 0.0 gLoss: 283.904 acc_g: 1.0
[[1174.20 0.00]
 [1236.96 5.33]
 [1631.97 11.89]
 [1426.47 27.89]
 [1534.22 27.65]
 [1584.57 26.06]
 [1883.54 27.85]
 [1826.62 22.16]
 [1739.06 27.79]
 [1695.90 26.77]
 [1553.58 21.13]
 [1550.83 20.41]
 [1536.83 19.12]
 [1493.37 16.82]
 [1399.70 16.98]]


Epoch: 24 dLossFake: 18.6933 acc_fake_train: 0.0 gLoss: 272.621 acc_g: 1.0
[[1172.27 0.00]
 [1256.57 5.07]
 [1374.65 12.93]
 [1651.72 33.29]
 [1494.84 21.21]
 [1404.59 23.35]
 [1556.94 28.06]
 [1702.46 22.66]
 [1755.31 20.86]
 [1814.69 25.41]
 [1687.98 22.82]
 [1643.52 23.28]
 [1648.71 21.68]
 [1699.22 19.56]
 [1605.15 18.85]]


Epoch: 25 dLossFake: 19.6232 acc_fake_train: 0.0 gLoss: 278.619 acc_g: 1.0
[[900.70 0.00]
 [1097.04 4.76]
 [1213.43 9.19]
 [1850.89 27.44]
 [1724.14 18.90]
 [1592.15 26.02]
 [1587.50 33.78]
 [1488.07 22.50]
 [1515.01 20.34]
 [1516.25 22.93]
 [1470.22 20.25]
 [1729.89 22.87]
 [1543.90 16.11]
 [1335.32 18.38]
 [1595.81 22.99]]


Epoch: 26 dLossFake: 18.7194 acc_fake_train: 0.0 gLoss: 270.926 acc_g: 1.0
[[1272.29 0.00]
 [1410.39 6.17]
 [1634.06 13.32]
 [1682.88 33.81]
 [1549.47 26.47]
 [1492.60 26.62]
 [1593.14 27.19]
 [1548.95 20.69]
 [1711.94 25.00]
 [1823.70 24.92]
 [1685.25 20.15]
 [1618.77 23.00]
 [1887.20 24.47]
 [1869.97 18.27]
 [1734.71 21.81]]


Epoch: 27 dLossFake: 19.5274 acc_fake_train: 0.0 gLoss: 269.92 acc_g: 1.0
[[1146.50 0.00]
 [1173.18 4.22]
 [1310.09 12.50]
 [1400.06 29.77]
 [1455.12 21.22]
 [1526.99 21.11]
 [1755.18 26.95]
 [1685.93 22.11]
 [1643.72 25.19]
 [1683.76 25.89]
 [1503.65 20.46]
 [1488.22 21.72]
 [1616.58 20.96]
 [1554.15 15.16]
 [1562.21 19.30]]


Epoch: 28 dLossFake: 19.2213 acc_fake_train: 0.0 gLoss: 251.923 acc_g: 1.0
[[1297.37 0.00]
 [1304.20 4.55]
 [1280.42 14.20]
 [1528.97 33.94]
 [1427.27 19.36]
 [1519.82 21.61]
 [1561.55 25.46]
 [1438.49 21.66]
 [1706.72 25.51]
 [1762.90 21.18]
 [1589.70 19.94]
 [1583.77 24.12]
 [1622.16 20.34]
 [1570.81 16.64]
 [1838.17 23.79]]


Epoch: 29 dLossFake: 19.778 acc_fake_train: 0.0 gLoss: 279.467 acc_g: 1.0
[[1135.89 0.00]
 [1028.89 3.28]
 [1496.36 13.07]
 [1579.62 30.09]
 [1753.95 23.44]
 [1520.55 24.24]
 [1678.08 31.36]
 [1659.08 23.34]
 [1714.70 23.67]
 [1692.68 24.15]
 [1493.31 22.04]
 [1558.72 21.67]
 [1490.04 17.74]
 [1619.84 19.10]
 [1646.36 19.17]]


Epoch: 30 dLossFake: 18.7897 acc_fake_train: 0.0 gLoss: 253.8 acc_g: 1.0
[[1160.33 0.00]
 [1107.47 3.91]
 [1426.28 13.47]
 [1450.10 29.77]
 [1585.11 22.38]
 [1467.47 22.86]
 [1496.27 26.30]
 [1477.83 22.15]
 [1818.10 25.74]
 [1652.79 18.83]
 [1672.97 24.56]
 [1717.92 24.75]
 [1670.08 18.92]
 [1443.34 19.22]
 [1592.71 22.75]]


Epoch: 31 dLossFake: 19.5539 acc_fake_train: 0.0 gLoss: 268.767 acc_g: 1.0
[[1224.62 0.00]
 [1298.78 5.71]
 [1326.35 13.45]
 [1473.19 32.85]
 [1515.07 22.83]
 [1474.01 21.50]
 [1400.19 25.63]
 [1601.78 24.23]
 [1512.46 18.15]
 [1511.70 22.69]
 [1601.28 23.48]
 [1769.61 20.36]
 [1778.33 20.01]
 [1631.86 22.02]
 [1578.45 22.72]]


Epoch: 32 dLossFake: 18.3422 acc_fake_train: 0.0 gLoss: 265.211 acc_g: 1.0
[[1353.77 0.00]
 [1228.96 4.17]
 [1384.95 16.28]
 [1512.04 33.23]
 [1567.51 21.10]
 [1514.34 21.61]
 [1705.77 28.05]
 [1574.60 21.98]
 [1564.60 25.01]
 [1736.37 25.46]
 [1478.50 16.38]
 [1383.99 20.96]
 [1522.61 21.93]
 [1418.83 13.30]
 [1512.18 17.37]]


Epoch: 33 dLossFake: 19.4057 acc_fake_train: 0.0 gLoss: 267.531 acc_g: 1.0
[[1009.99 0.00]
 [1183.30 5.52]
 [1407.69 10.35]
 [1424.60 27.66]
 [1428.76 24.43]
 [1599.26 24.48]
 [1605.97 23.51]
 [1590.64 24.56]
 [1670.42 25.12]
 [1518.71 21.59]
 [1604.23 23.84]
 [1656.10 21.56]
 [1589.95 19.71]
 [1507.54 20.25]
 [1483.45 19.36]]


Epoch: 34 dLossFake: 19.4135 acc_fake_train: 0.0 gLoss: 229.548 acc_g: 1.0
[[1252.32 0.00]
 [1085.87 3.04]
 [1313.72 15.11]
 [1452.32 31.02]
 [1509.38 19.94]
 [1500.95 22.06]
 [1738.92 29.02]
 [1776.42 22.42]
 [1550.63 23.10]
 [1709.83 27.75]
 [1602.38 20.12]
 [1509.41 19.79]
 [1656.19 23.40]
 [1563.05 16.75]
 [1655.43 19.39]]


Epoch: 35 dLossFake: 19.864 acc_fake_train: 0.0 gLoss: 248.49 acc_g: 1.0
[[1408.63 0.00]
 [1341.46 4.87]
 [1395.63 17.17]
 [1504.38 35.11]
 [1426.35 21.52]
 [1652.81 23.72]
 [1566.66 23.59]
 [1581.29 24.79]
 [1531.36 23.52]
 [1385.43 21.21]
 [1551.66 21.44]
 [1581.84 18.60]
 [1603.59 18.27]
 [1595.84 20.87]
 [1695.19 21.77]]


KeyboardInterrupt: 