In [1]:
import os
from datetime import datetime

#PROJECT_ROOT_DIR = "/home/ubuntu/TroubledLife"
PROJECT_ROOT_DIR = "/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife"
TF_LOG_DIR = os.path.join(PROJECT_ROOT_DIR, "tf_logs")
MODEL_CHECKPOINTS_DIR = os.path.join(PROJECT_ROOT_DIR, "model_checkpoints")

now = datetime.now().strftime("%Y%m%d-%H%M%S")
log_dir = "{}/run-{}/".format(TF_LOG_DIR, now)


import data_preparation as dp

runtime = 5


def generator_loss(Gz, init_z):
    premium = init_z[:, 0]
    interest = init_z[:, 1] * 0.03 + init_z[:, 2] * 0.04 + init_z[:, 3] * 0.05 + init_z[:, 4] * 0.06
    
    k1 = premium
    k1v = k1 * (1 + interest)
    k2 = premium + k1v
    k2v = k2 * (1 + interest)
    k3 = premium + k2v
    k3v = k3 * (1 + interest)
    k4 = premium + k3v
    k4v = k4 * (1 + interest)
    k5 = premium + k4v
    k5v = k5 * (1 + interest)
    
    # loss = (tf.abs(Gz[:, 0, 0] - premium) + tf.abs(Gz[:, 0, 1]) +
    #                        tf.abs(Gz[:, 1, 0] - premium) + tf.abs(Gz[:, 1, 1] - k1) +
    #                        tf.abs(Gz[:, 2, 0] - premium) + tf.abs(Gz[:, 2, 1] - k1v) +
    #                        tf.abs(Gz[:, 3, 0] - premium) + tf.abs(Gz[:, 3, 1] - k2) +
    #                        tf.abs(Gz[:, 4, 0] - premium) + tf.abs(Gz[:, 4, 1] - k2v) +
    #                        tf.abs(Gz[:, 5, 0] - premium) + tf.abs(Gz[:, 5, 1] - k3) +
    #                        tf.abs(Gz[:, 6, 0] - premium) + tf.abs(Gz[:, 6, 1] - k3v) +
    #                        tf.abs(Gz[:, 7, 0] - premium) + tf.abs(Gz[:, 7, 1] - k4) +
    #                        tf.abs(Gz[:, 8, 0] - premium) + tf.abs(Gz[:, 8, 1] - k4v) +
    #                        tf.abs(Gz[:, 9, 0] - premium) + tf.abs(Gz[:, 9, 1] - k5) +
    #                        tf.abs(Gz[:, 10, 0] - premium) + tf.abs(Gz[:, 10, 1] - k5v)
    #                        )
    
    boost = 1

    loss = (tf.pow(boost * (Gz[:, 0, 0] - premium), 2) + tf.pow(Gz[:, 0, 1], 2) +
                           tf.pow(boost * (Gz[:, 1, 0] - premium), 2) + tf.pow(boost * (Gz[:, 1, 1] - k1), 2) +
                           tf.pow(boost * (Gz[:, 2, 0] - premium), 2) + tf.pow(boost * (Gz[:, 2, 1] - k1v), 2) +
                           tf.pow(boost * (Gz[:, 3, 0] - premium), 2) + tf.pow(boost * (Gz[:, 3, 1] - k2), 2) +
                           tf.pow(boost * (Gz[:, 4, 0] - premium), 2) + tf.pow(boost * (Gz[:, 4, 1] - k2v), 2) +
                           tf.pow(boost * (Gz[:, 5, 0] - premium), 2) + tf.pow(boost * (Gz[:, 5, 1] - k3), 2) +
                           tf.pow(boost * (Gz[:, 6, 0] - premium), 2) + tf.pow(boost * (Gz[:, 6, 1] - k3v), 2) +
                           tf.pow(boost * (Gz[:, 7, 0] - premium), 2) + tf.pow(boost * (Gz[:, 7, 1] - k4), 2) +
                           tf.pow(boost * (Gz[:, 8, 0] - premium), 2) + tf.pow(boost * (Gz[:, 8, 1] - k4v), 2) +
                           tf.pow(boost * (Gz[:, 9, 0] - premium), 2) + tf.pow(boost * (Gz[:, 9, 1] - k5), 2) +
                           tf.pow(boost * (Gz[:, 10, 0] - premium), 2) + tf.pow(boost * (Gz[:, 10, 1] - k5v), 2)
                           )
    loss_mean = tf.reduce_mean(tf.sqrt(loss))
                           
    # loss_mean = tf.reduce_mean(tf.abs(Gz[:, 0, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 0, 1])) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 1, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 1, 1] - k1)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 2, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 2, 1] - k1v)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 3, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 3, 1] - k2)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 4, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 4, 1] - k2v)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 5, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 5, 1] - k3)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 6, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 6, 1] - k3v)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 7, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 7, 1] - k4)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 8, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 8, 1] - k4v)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 9, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 9, 1] - k5)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 10, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 10, 1] - k5v))

    #loss_mean = tf.reduce_mean(loss)
    
    return loss_mean, loss



In [6]:
import tensorflow as tf
import gan as gan

size_batch = 200
max_length_policy_history=15

# Generator hyperparameters
cell_type_g="LayerNormLSTM"
leaky_g=False
n_inputs_g = 5
n_layers_g = 2
n_neurons_g = 40
n_outputs_g = 2
input_keep_prob_g = 1.0
learning_rate_g = 1e-04
beta1_g=0.9
beta2_g=0.999
epsilon_g=1e-08
clip_g=True
threshold_g = 1.0

tf.reset_default_graph()
tf.set_random_seed(42)

Z = tf.placeholder(tf.float32, [None, max_length_policy_history, n_inputs_g], name='Z')
init_z = tf.placeholder(tf.float32, [None, n_inputs_g], name='init_z')
seq_length_z = tf.placeholder(tf.int32, [None], name='seq_length_z')

Gz = gan.generator(Z=Z, n_outputs=n_outputs_g, 
                   n_layers=n_layers_g, n_neurons=n_neurons_g, 
                   seq_length=seq_length_z, cell_type=cell_type_g, leaky=leaky_g, input_keep_prob=input_keep_prob_g)

loss_mean_g, loss_g = generator_loss(Gz=Gz, init_z=init_z)

g_trainer = gan.generator_trainer(learning_rate=learning_rate_g, beta1=beta1_g, beta2=beta2_g, epsilon=epsilon_g, 
                                  clip=clip_g, threshold=threshold_g, loss=loss_mean_g)

tf.summary.scalar('Generator_loss', loss_mean_g)

merged = tf.summary.merge_all()
writer = tf.summary.FileWriter(log_dir, tf.get_default_graph())

tvars = tf.trainable_variables()

g_saver = tf.train.Saver(var_list=[var for var in tvars if "t_generator" in var.name])

In [7]:
import numpy as np

np.set_printoptions(formatter={'float_kind': (lambda x: "%.2f" % x)})

sess = tf.Session()

sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

In [10]:
g_saver.restore(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "generator.ckpt"))

n_epochs = 400
num_examples = 10000

for epoch in range(n_epochs):
    for batch in range(num_examples // size_batch):
        Z_batch, seq_length_z_batch, init_z_batch = dp.generate_Z_batch(
            size_batch=size_batch, max_length_policy_history=max_length_policy_history, 
            n_inputs = n_inputs_g, runtime=runtime)

        _, lossMeanG, lossG, gData = \
            sess.run([g_trainer, loss_mean_g, loss_g, Gz], 
                     feed_dict={Z: Z_batch, seq_length_z: seq_length_z_batch, init_z: init_z_batch})

    summary = sess.run(merged, feed_dict={Z: Z_batch, seq_length_z: seq_length_z_batch, init_z: init_z_batch})
    writer.add_summary(summary, epoch)

    print("Epoch:", epoch, "lossG:", lossMeanG)
    
#    print(lossMeanG[0])
    print(Z_batch[0, 0])
    print(gData[0])
    
g_saver.save(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "generator3.ckpt"))    

INFO:tensorflow:Restoring parameters from /Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife/model_checkpoints/generator.ckpt


Epoch: 0 lossG: 1531.19
[1239.07 1.00 0.00 0.00 0.00]
[[1255.46 -0.22]
 [1265.42 1280.47]
 [1273.87 1336.63]
 [1260.38 2601.33]
 [1278.40 2740.29]
 [1258.17 3931.17]
 [1269.28 4014.84]
 [1248.97 5238.22]
 [1234.34 5427.68]
 [1234.90 6695.07]
 [1230.51 6912.21]
 [5.59 11.89]
 [5.59 11.89]
 [5.59 11.89]
 [5.59 11.89]]


Epoch: 1 lossG: 1491.95
[1356.38 1.00 0.00 0.00 0.00]
[[1245.89 -0.12]
 [1257.14 1245.07]
 [1245.65 1283.04]
 [1251.72 2493.19]
 [1240.30 2566.58]
 [1237.99 3789.91]
 [1251.80 3909.95]
 [1233.29 5141.86]
 [1224.12 5286.45]
 [1250.08 6565.60]
 [1239.31 6796.13]
 [5.58 11.87]
 [5.58 11.87]
 [5.58 11.87]
 [5.58 11.87]]


Epoch: 2 lossG: 1500.38
[1288.53 1.00 0.00 0.00 0.00]
[[1238.87 8.42]
 [1235.43 1230.84]
 [1232.08 1264.24]
 [1257.98 2492.71]
 [1230.65 2553.77]
 [1223.46 3807.84]
 [1227.94 3894.13]
 [1218.00 5123.53]
 [1239.33 5263.23]
 [1229.91 6514.03]
 [1241.65 6751.96]
 [5.57 11.88]
 [5.57 11.88]
 [5.57 11.88]
 [5.57 11.88]]


Epoch: 3 lossG: 1407.86
[1161.72 1.00 0.00 0.00 0.00]
[[1238.25 -9.23]
 [1245.08 1217.12]
 [1233.01 1234.67]
 [1248.97 2475.80]
 [1241.39 2511.23]
 [1240.59 3830.41]
 [1241.13 3941.95]
 [1271.02 5215.66]
 [1255.63 5346.96]
 [1257.32 6599.93]
 [1260.86 6809.25]
 [5.59 11.86]
 [5.59 11.86]
 [5.59 11.86]
 [5.59 11.86]]


Epoch: 4 lossG: 1410.49
[1073.91 1.00 0.00 0.00 0.00]
[[1250.37 4.85]
 [1252.84 1242.27]
 [1244.67 1244.54]
 [1273.21 2465.20]
 [1245.51 2466.59]
 [1234.32 3772.36]
 [1244.24 3890.42]
 [1254.57 5194.05]
 [1266.03 5371.59]
 [1275.52 6643.84]
 [1268.13 6854.88]
 [5.59 11.86]
 [5.59 11.86]
 [5.59 11.86]
 [5.59 11.86]]


Epoch: 5 lossG: 1492.75
[1486.19 1.00 0.00 0.00 0.00]
[[1237.65 3.46]
 [1241.09 1224.83]
 [1241.93 1244.69]
 [1237.56 2491.13]
 [1243.87 2546.72]
 [1232.64 3812.27]
 [1246.62 3976.20]
 [1249.72 5198.46]
 [1253.38 5367.80]
 [1240.81 6606.49]
 [1251.34 6816.73]
 [5.60 11.86]
 [5.60 11.86]
 [5.60 11.86]
 [5.60 11.86]]


Epoch: 6 lossG: 1458.94
[1428.82 1.00 0.00 0.00 0.00]
[[1244.51 -4.86]
 [1238.86 1240.89]
 [1238.34 1299.67]
 [1241.59 2544.71]
 [1250.98 2639.81]
 [1255.32 3857.66]
 [1251.26 3979.15]
 [1248.14 5201.76]
 [1252.84 5364.98]
 [1242.09 6602.77]
 [1239.10 6798.35]
 [5.60 11.88]
 [5.60 11.88]
 [5.60 11.88]
 [5.60 11.88]]


Epoch: 7 lossG: 1632.89
[1196.90 1.00 0.00 0.00 0.00]
[[1262.19 9.90]
 [1257.13 1263.39]
 [1259.95 1291.92]
 [1275.79 2560.32]
 [1259.07 2617.44]
 [1272.60 3955.12]
 [1268.82 4052.54]
 [1277.25 5379.49]
 [1281.11 5515.42]
 [1266.87 6780.62]
 [1265.75 6927.48]
 [5.61 11.89]
 [5.61 11.89]
 [5.61 11.89]
 [5.61 11.89]]


Epoch: 8 lossG: 1423.85
[1383.32 1.00 0.00 0.00 0.00]
[[1240.81 -3.18]
 [1252.63 1269.95]
 [1251.78 1321.72]
 [1250.36 2591.44]
 [1242.85 2685.02]
 [1250.03 3887.25]
 [1248.51 3998.44]
 [1240.70 5212.51]
 [1246.44 5378.71]
 [1236.37 6630.63]
 [1240.94 6841.69]
 [5.62 11.87]
 [5.62 11.87]
 [5.62 11.87]
 [5.62 11.87]]


Epoch: 9 lossG: 1413.52
[1336.97 1.00 0.00 0.00 0.00]
[[1254.68 14.09]
 [1254.84 1289.12]
 [1256.35 1332.84]
 [1254.21 2639.73]
 [1262.94 2744.24]
 [1265.63 3966.16]
 [1265.87 4088.32]
 [1266.57 5301.11]
 [1266.47 5449.88]
 [1257.46 6686.51]
 [1258.88 6874.70]
 [5.62 11.87]
 [5.62 11.87]
 [5.62 11.87]
 [5.62 11.87]]


Epoch: 10 lossG: 1450.5
[1071.53 1.00 0.00 0.00 0.00]
[[1244.45 -9.05]
 [1249.40 1242.80]
 [1247.04 1297.87]
 [1254.48 2554.37]
 [1247.63 2626.61]
 [1259.43 3872.22]
 [1255.07 3984.42]
 [1252.22 5226.74]
 [1260.85 5396.08]
 [1253.41 6643.95]
 [1252.95 6847.43]
 [5.63 11.88]
 [5.63 11.88]
 [5.63 11.88]
 [5.63 11.88]]


Epoch: 11 lossG: 1407.43
[1128.11 1.00 0.00 0.00 0.00]
[[1251.54 -8.64]
 [1255.94 1248.79]
 [1255.57 1293.11]
 [1263.10 2530.02]
 [1247.46 2612.80]
 [1248.59 3881.25]
 [1249.19 3995.51]
 [1247.79 5243.67]
 [1245.62 5411.58]
 [1254.38 6674.20]
 [1254.71 6877.21]
 [5.63 11.88]
 [5.63 11.88]
 [5.63 11.88]
 [5.63 11.88]]


Epoch: 12 lossG: 1443.16
[1352.05 1.00 0.00 0.00 0.00]
[[1253.14 3.38]
 [1248.11 1273.66]
 [1247.82 1328.53]
 [1240.32 2587.21]
 [1242.14 2699.43]
 [1248.46 3897.45]
 [1242.27 4027.96]
 [1239.96 5220.92]
 [1237.94 5376.00]
 [1226.87 6597.37]
 [1228.31 6800.57]
 [5.63 11.88]
 [5.63 11.88]
 [5.63 11.88]
 [5.63 11.88]]


Epoch: 13 lossG: 1512.58
[1155.61 1.00 0.00 0.00 0.00]
[[1256.92 2.96]
 [1251.86 1246.66]
 [1248.65 1272.53]
 [1245.14 2506.14]
 [1258.39 2553.62]
 [1248.68 3823.66]
 [1243.10 3928.93]
 [1249.90 5216.62]
 [1251.91 5386.38]
 [1254.74 6653.18]
 [1249.42 6851.41]
 [5.64 11.89]
 [5.64 11.89]
 [5.64 11.89]
 [5.64 11.89]]


Epoch: 14 lossG: 1597.1
[1072.35 1.00 0.00 0.00 0.00]
[[1247.95 0.41]
 [1253.26 1266.70]
 [1255.50 1305.31]
 [1246.79 2558.78]
 [1248.90 2650.69]
 [1244.64 3886.62]
 [1248.53 4002.77]
 [1252.56 5234.89]
 [1250.42 5391.66]
 [1234.63 6652.09]
 [1241.05 6847.02]
 [5.64 11.88]
 [5.64 11.88]
 [5.64 11.88]
 [5.64 11.88]]


Epoch: 15 lossG: 1478.48
[1097.58 1.00 0.00 0.00 0.00]
[[1244.54 -2.40]
 [1238.48 1240.57]
 [1234.08 1275.84]
 [1235.55 2527.78]
 [1234.93 2592.55]
 [1236.06 3838.30]
 [1237.74 3959.45]
 [1237.31 5211.92]
 [1235.02 5371.45]
 [1240.56 6618.67]
 [1240.34 6827.51]
 [5.63 11.87]
 [5.63 11.87]
 [5.63 11.87]
 [5.63 11.87]]


Epoch: 16 lossG: 1502.43
[1449.56 1.00 0.00 0.00 0.00]
[[1257.15 5.63]
 [1249.96 1278.39]
 [1249.00 1308.98]
 [1233.93 2590.64]
 [1249.55 2674.73]
 [1254.67 3896.40]
 [1248.89 4005.49]
 [1252.71 5235.94]
 [1252.15 5387.64]
 [1248.66 6631.71]
 [1238.94 6824.73]
 [5.62 11.89]
 [5.62 11.89]
 [5.62 11.89]
 [5.62 11.89]]


KeyboardInterrupt: 

In [9]:
g_saver.save(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "generator.ckpt"))

 

'/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife/model_checkpoints/generator.ckpt'