In [1]:
import support_functions as sf

sf.generate_very_simple_portfolio_history(no_of_policies=10000, runtime=5)

In [2]:
policy_histories = sf.load_troubled_life_policy_data()
#po licy_histories

In [3]:
policy_histories, history_lengths, max_history_length = sf.prepare_troubled_life_policy_data(policy_histories=policy_histories)
#policy_histories


In [4]:
# Extract features and labels from dataset as numpy.ndarray(s)
policy_histories_labels = policy_histories['troubled'].as_matrix()
policy_histories_features = policy_histories[['premium', 'current_capital']].as_matrix()

# Reshape features from (overall_no_of_histories, 2) to (overall_no_of_policies, maximum_history_length, 2)
policy_histories_features = policy_histories_features.reshape((policy_histories.index.levels[0].shape[0], max_history_length, -1))

# Reshape labels from (overall_no_of_histories) to (overall_no_of_policies, maximum_history_length) and take maximum of each row (0 or 1)
policy_histories_labels = policy_histories_labels.reshape(policy_histories.index.levels[0].shape[0], -1).max(axis=1)

history_lengths = history_lengths[:,1]

#policy_histories_features, policy_histories_labels, history_lengths

In [8]:
import tensorflow as tf
from datetime import datetime

now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
root_logdir = "/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife/tf_logs"
logdir = "{}/run-{}/".format(root_logdir, now)

tf.reset_default_graph()
tf.set_random_seed(42)

n_steps = max_history_length
n_inputs = 2

n_neurons = 20
n_outputs = 2

learning_rate = 0.001

# Placeholders for our input sequences
seq_length = tf.placeholder(tf.int32, [None])
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.int32, [None])

# A single RNN layer of n_neurons neurons
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32, sequence_length=seq_length)

# We feed the layer's output of the last timestep into a fully connected layer of 2 neurons
# (1 per class, troubled or not). Softmax layer is next
logits = tf.layers.dense(states, n_outputs)
y_pred = tf.argmax(tf.nn.softmax(logits), axis=1)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)
#xentropy = y - y_pred
#xentropy = tf.abs(xentropy)

# Loss function and Adam Optimizer
loss = tf.reduce_mean(tf.cast(xentropy, tf.float32))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

correct = tf.nn.in_top_k(logits, y, 1)
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

init = tf.global_variables_initializer()

loss_summary = tf.summary.scalar('Loss', loss)
file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

In [9]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

n_epochs = 100
batch_size = 1000

X_batch = policy_histories_features
y_batch = policy_histories_labels
seq_length_batch = history_lengths

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for i in range(policy_histories_labels.shape[0] // batch_size):
            X_batch = policy_histories_features[i * batch_size : (i + 1) * batch_size]
            y_batch = policy_histories_labels[i * batch_size : (i + 1) * batch_size]
            seq_length_batch = history_lengths[i * batch_size : (i + 1) * batch_size]
            
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
            #print(outputs.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch}))
        #print(logits.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch}))
        y_batch_pred = y_pred.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        acc_train = accuracy.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        #acc_test = accuracy.eval(feed_dict={X: X_test, y: y_test})
        print(epoch, "Train accuracy:", acc_train)#, "Test accuracy:", acc_test)
        print(loss.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch}))
        print(confusion_matrix(y_batch, y_batch_pred))
        print(classification_report(y_batch, y_batch_pred, target_names=['ok', 'troubled']))

        summary_str = loss_summary.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        file_writer.add_summary(summary_str, epoch)

file_writer.close()

0 Train accuracy: 0.783
349.036
[[783   0]
 [217   0]]
             precision    recall  f1-score   support

         ok       0.78      1.00      0.88       783
   troubled       0.00      0.00      0.00       217

avg / total       0.61      0.78      0.69      1000

1 Train accuracy: 0.783
48.8602
[[783   0]
 [217   0]]
             precision    recall  f1-score   support

         ok       0.78      1.00      0.88       783
   troubled       0.00      0.00      0.00       217

avg / total       0.61      0.78      0.69      1000



/Users/gopora/MyStuff/Dev/miniconda3/envs/pie35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


2 Train accuracy: 0.783
37.3777
[[783   0]
 [217   0]]
             precision    recall  f1-score   support

         ok       0.78      1.00      0.88       783
   troubled       0.00      0.00      0.00       217

avg / total       0.61      0.78      0.69      1000

3 Train accuracy: 0.784
15.3715
[[783   0]
 [216   1]]
             precision    recall  f1-score   support

         ok       0.78      1.00      0.88       783
   troubled       1.00      0.00      0.01       217

avg / total       0.83      0.78      0.69      1000



4 Train accuracy: 0.783
20.9285
[[783   0]
 [217   0]]
             precision    recall  f1-score   support

         ok       0.78      1.00      0.88       783
   troubled       0.00      0.00      0.00       217

avg / total       0.61      0.78      0.69      1000

5 Train accuracy: 0.862
5.05843
[[783   0]
 [138  79]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       783
   troubled       1.00      0.36      0.53       217

avg / total       0.88      0.86      0.84      1000

6 Train accuracy: 0.864
3.45561
[[783   0]
 [136  81]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       783
   troubled       1.00      0.37      0.54       217

avg / total       0.88      0.86      0.84      1000



7 Train accuracy: 0.914
2.88703
[[783   0]
 [ 86 131]]
             precision    recall  f1-score   support

         ok       0.90      1.00      0.95       783
   troubled       1.00      0.60      0.75       217

avg / total       0.92      0.91      0.91      1000

8 Train accuracy: 0.853
6.19828
[[783   0]
 [147  70]]
             precision    recall  f1-score   support

         ok       0.84      1.00      0.91       783
   troubled       1.00      0.32      0.49       217

avg / total       0.88      0.85      0.82      1000



9 Train accuracy: 0.912
2.60568
[[783   0]
 [ 88 129]]
             precision    recall  f1-score   support

         ok       0.90      1.00      0.95       783
   troubled       1.00      0.59      0.75       217

avg / total       0.92      0.91      0.90      1000

10 Train accuracy: 0.853
6.03995
[[783   0]
 [147  70]]
             precision    recall  f1-score   support

         ok       0.84      1.00      0.91       783
   troubled       1.00      0.32      0.49       217

avg / total       0.88      0.85      0.82      1000

11 Train accuracy: 0.864
3.20887
[[783   0]
 [136  81]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       783
   troubled       1.00      0.37      0.54       217

avg / total       0.88      0.86      0.84      1000



12 Train accuracy: 0.852
6.17494
[[783   0]
 [148  69]]
             precision    recall  f1-score   support

         ok       0.84      1.00      0.91       783
   troubled       1.00      0.32      0.48       217

avg / total       0.88      0.85      0.82      1000

13 Train accuracy: 0.902
2.48262
[[783   0]
 [ 98 119]]
             precision    recall  f1-score   support

         ok       0.89      1.00      0.94       783
   troubled       1.00      0.55      0.71       217

avg / total       0.91      0.90      0.89      1000

14 Train accuracy: 0.864
4.28019
[[783   0]
 [136  81]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       783
   troubled       1.00      0.37      0.54       217

avg / total       0.88      0.86      0.84      1000



15 Train accuracy: 0.176
2.29298
[[  0 783]
 [ 41 176]]
             precision    recall  f1-score   support

         ok       0.00      0.00      0.00       783
   troubled       0.18      0.81      0.30       217

avg / total       0.04      0.18      0.06      1000

16 Train accuracy: 0.864
3.40703
[[783   0]
 [136  81]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       783
   troubled       1.00      0.37      0.54       217

avg / total       0.88      0.86      0.84      1000

17 Train accuracy: 0.178
5.18016
[[  0 783]
 [ 39 178]]
             precision    recall  f1-score   support

         ok       0.00      0.00      0.00       783
   troubled       0.19      0.82      0.30       217

avg / total       0.04      0.18      0.07      1000



18 Train accuracy: 0.877
2.80248
[[783   0]
 [123  94]]
             precision    recall  f1-score   support

         ok       0.86      1.00      0.93       783
   troubled       1.00      0.43      0.60       217

avg / total       0.89      0.88      0.86      1000

19 Train accuracy: 0.178
6.2949
[[  0 783]
 [ 39 178]]
             precision    recall  f1-score   support

         ok       0.00      0.00      0.00       783
   troubled       0.19      0.82      0.30       217

avg / total       0.04      0.18      0.07      1000

20 Train accuracy: 0.898
2.10021
[[783   0]
 [102 115]]
             precision    recall  f1-score   support

         ok       0.88      1.00      0.94       783
   troubled       1.00      0.53      0.69       217

avg / total       0.91      0.90      0.89      1000



21 Train accuracy: 0.18
3.67024
[[  0 783]
 [ 37 180]]
             precision    recall  f1-score   support

         ok       0.00      0.00      0.00       783
   troubled       0.19      0.83      0.31       217

avg / total       0.04      0.18      0.07      1000

22 Train accuracy: 0.854
4.48393
[[783   0]
 [146  71]]
             precision    recall  f1-score   support

         ok       0.84      1.00      0.91       783
   troubled       1.00      0.33      0.49       217

avg / total       0.88      0.85      0.82      1000

23 Train accuracy: 0.891
2.25013
[[783   0]
 [109 108]]
             precision    recall  f1-score   support

         ok       0.88      1.00      0.93       783
   troubled       1.00      0.50      0.66       217

avg / total       0.90      0.89      0.88      1000



24 Train accuracy: 0.958
0.99298
[[783   0]
 [ 42 175]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       783
   troubled       1.00      0.81      0.89       217

avg / total       0.96      0.96      0.96      1000

25 Train accuracy: 0.964
0.934626
[[783   0]
 [ 36 181]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.83      0.91       217

avg / total       0.97      0.96      0.96      1000

26 Train accuracy: 0.965
0.788016
[[783   0]
 [ 35 182]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.84      0.91       217

avg / total       0.97      0.96      0.96      1000



27 Train accuracy: 0.862
2.81678
[[783   0]
 [138  79]]
             precision    recall  f1-score   support

         ok       0.85      1.00      0.92       783
   troubled       1.00      0.36      0.53       217

avg / total       0.88      0.86      0.84      1000

28 Train accuracy: 0.856
3.66721
[[783   0]
 [144  73]]
             precision    recall  f1-score   support

         ok       0.84      1.00      0.92       783
   troubled       1.00      0.34      0.50       217

avg / total       0.88      0.86      0.83      1000

29 Train accuracy: 0.966
0.792124
[[783   0]
 [ 34 183]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.84      0.92       217

avg / total       0.97      0.97      0.96      1000



30 Train accuracy: 0.966
0.475591
[[783   0]
 [ 34 183]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.84      0.92       217

avg / total       0.97      0.97      0.96      1000

31 Train accuracy: 0.966
0.396498
[[783   0]
 [ 34 183]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.84      0.92       217

avg / total       0.97      0.97      0.96      1000

32 Train accuracy: 0.966
0.333308
[[783   0]
 [ 34 183]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.84      0.92       217

avg / total       0.97      0.97      0.96      1000



33 Train accuracy: 0.966
0.264409
[[783   0]
 [ 34 183]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.84      0.92       217

avg / total       0.97      0.97      0.96      1000

34 Train accuracy: 0.966
0.234528
[[783   0]
 [ 34 183]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.84      0.92       217

avg / total       0.97      0.97      0.96      1000

35 Train accuracy: 0.94
0.384414
[[783   0]
 [ 60 157]]
             precision    recall  f1-score   support

         ok       0.93      1.00      0.96       783
   troubled       1.00      0.72      0.84       217

avg / total       0.94      0.94      0.94      1000



36 Train accuracy: 0.217
0.727444
[[  0 783]
 [  0 217]]
             precision    recall  f1-score   support

         ok       0.00      0.00      0.00       783
   troubled       0.22      1.00      0.36       217

avg / total       0.05      0.22      0.08      1000

37 Train accuracy: 0.959
0.138564
[[783   0]
 [ 41 176]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       783
   troubled       1.00      0.81      0.90       217

avg / total       0.96      0.96      0.96      1000

38 Train accuracy: 0.967
0.0706346
[[783   0]
 [ 33 184]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       783
   troubled       1.00      0.85      0.92       217

avg / total       0.97      0.97      0.97      1000



39 Train accuracy: 0.992
0.0134887
[[783   0]
 [  8 209]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       783
   troubled       1.00      0.96      0.98       217

avg / total       0.99      0.99      0.99      1000

40 Train accuracy: 1.0
0.014766
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

41 Train accuracy: 1.0
0.00839168
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



42 Train accuracy: 1.0
0.00630424
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

43 Train accuracy: 1.0
0.0059703
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

44 Train accuracy: 1.0
0.0057415
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



45 Train accuracy: 1.0
0.00552395
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

46 Train accuracy: 1.0
0.0053831
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

47 Train accuracy: 1.0
0.0052536
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



48 Train accuracy: 1.0
0.00510331
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

49 Train accuracy: 1.0
0.00495214
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

50 Train accuracy: 1.0
0.00481452
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



51 Train accuracy: 1.0
0.00469372
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

52 Train accuracy: 1.0
0.00458179
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

53 Train accuracy: 1.0
0.00447602
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



54 Train accuracy: 1.0
0.00437427
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

55 Train accuracy: 1.0
0.00427767
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

56 Train accuracy: 1.0
0.00418616
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



57 Train accuracy: 1.0
0.00409898
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

58 Train accuracy: 1.0
0.004016
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

59 Train accuracy: 1.0
0.00393591
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



60 Train accuracy: 1.0
0.00385961
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

61 Train accuracy: 1.0
0.00378658
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

62 Train accuracy: 1.0
0.00371625
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



63 Train accuracy: 1.0
0.00364777
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

64 Train accuracy: 1.0
0.00358308
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

65 Train accuracy: 1.0
0.00352016
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



66 Train accuracy: 1.0
0.0034591
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

67 Train accuracy: 1.0
0.00340026
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

68 Train accuracy: 1.0
0.00334386
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



69 Train accuracy: 1.0
0.00328861
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

70 Train accuracy: 1.0
0.0032351
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

71 Train accuracy: 1.0
0.00318389
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



72 Train accuracy: 1.0
0.00313317
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

73 Train accuracy: 1.0
0.00308394
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

74 Train accuracy: 1.0
0.00303596
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



75 Train accuracy: 1.0
0.00299412
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

76 Train accuracy: 1.0
0.00295549
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

77 Train accuracy: 1.0
0.00291692
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



78 Train accuracy: 1.0
0.00287776
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

79 Train accuracy: 1.0
0.0028415
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

80 Train accuracy: 1.0
0.00280591
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



81 Train accuracy: 1.0
0.0027694
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

82 Train accuracy: 1.0
0.00273581
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

83 Train accuracy: 1.0
0.00270197
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



84 Train accuracy: 1.0
0.00266953
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

85 Train accuracy: 1.0
0.00263673
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

86 Train accuracy: 1.0
0.002606
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



87 Train accuracy: 1.0
0.00257494
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

88 Train accuracy: 1.0
0.00254463
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

89 Train accuracy: 1.0
0.00251554
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



90 Train accuracy: 1.0
0.00248696
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

91 Train accuracy: 1.0
0.00245772
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

92 Train accuracy: 1.0
0.00243077
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



93 Train accuracy: 1.0
0.00240257
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

94 Train accuracy: 1.0
0.00237608
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

95 Train accuracy: 1.0
0.00234905
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



96 Train accuracy: 1.0
0.00232308
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

97 Train accuracy: 1.0
0.00229802
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

98 Train accuracy: 1.0
0.00227236
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000



99 Train accuracy: 1.0
0.00224822
[[783   0]
 [  0 217]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       783
   troubled       1.00      1.00      1.00       217

avg / total       1.00      1.00      1.00      1000

