In [1]:
import os
from datetime import datetime

PROJECT_ROOT_DIR = "/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife"
DATASETS_DIR = os.path.join(PROJECT_ROOT_DIR, "data")
TF_LOG_DIR = os.path.join(PROJECT_ROOT_DIR, "tf_logs")
MODEL_CHECKPOINTS_DIR = os.path.join(PROJECT_ROOT_DIR, "model_checkpoints")
TRAINING_SET_DATA_FILE = "troubled_life_policy_train_data.csv"
TEST_SET_DATA_FILE = "troubled_life_policy_test_data.csv"

now = datetime.now().strftime("%Y%m%d-%H%M%S")
log_dir = "{}/run-{}/".format(TF_LOG_DIR, now)


import data_preparation as dp

#dp.generate_troubled_life_policy_data(no_of_policies=10000, runtime=5, file_path=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))

#dp.generate_troubled_life_policy_data(no_of_policies=2000, runtime=5, file_path=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

policy_histories_train = \
    dp.load_troubled_life_policy_data(file_path=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))

policy_histories_test = \
    dp.load_troubled_life_policy_data(file_path=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

policy_histories_length_train, max_policy_history_length_train = \
    dp.get_policy_history_lengths(policy_histories=policy_histories_train)

policy_histories_length_test, max_policy_history_length_test = \
    dp.get_policy_history_lengths(policy_histories=policy_histories_test)

max_policy_history_length = max(max_policy_history_length_train, max_policy_history_length_test)



# Pad the histories up to maximum length of both, train and test set

# policy_histories_train = \
#     dp.pad_troubled_life_policy_histories(policy_histories=policy_histories_train,
#                                           policy_histories_lengths=policy_histories_length_train,
#                                           max_policy_history_length=max_policy_history_length)
# 
# policy_histories_test = \
#     dp.pad_troubled_life_policy_histories(policy_histories=policy_histories_test,
#                                           policy_histories_lengths=policy_histories_length_test,
#                                           max_policy_history_length=max_policy_history_length)
# 
# # # Save padded data, since always generating and padding takes too long
# policy_histories_train.to_csv(path_or_buf=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))
# policy_histories_test.to_csv(path_or_buf=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

# Extract features and labels from dataset as numpy.ndarray(s)
binary_classification = True

train_labels, train_features, train_seq_lengths =\
    dp.prepare_labels_features_lengths(policy_histories=policy_histories_train,
                                       policy_histories_lengths=policy_histories_length_train, 
                                       max_policy_history_length=max_policy_history_length,
                                       binary_classification=binary_classification)
test_labels, test_features, test_seq_lengths =\
    dp.prepare_labels_features_lengths(policy_histories=policy_histories_test,
                                       policy_histories_lengths=policy_histories_length_test, 
                                       max_policy_history_length=max_policy_history_length,
                                       binary_classification=binary_classification)

train_data = dp.TrainDataSet(train_labels=train_labels, train_features=train_features, train_seq_lengths=train_seq_lengths)

In [2]:
import tensorflow as tf
import gan as gan


g_learning_rate = 0.01
d_real_learning_rate = 0.0001
d_fake_learning_rate = 0.0001
noise_dimensions = 2
batch_size = 200
g_n_outputs = 2
d_n_inputs = 2
d_n_outputs = 2 if binary_classification else max_policy_history_length

tf.reset_default_graph()
tf.set_random_seed(42)

noise = tf.placeholder(tf.float32, [batch_size, max_policy_history_length, noise_dimensions], name='noise')
noise_seq_length = tf.placeholder(tf.int32, [None], name='noise_seq_length')

X = tf.placeholder(tf.float32, [None, max_policy_history_length, d_n_inputs], name="X")
y = tf.placeholder(tf.int32, [None], name="y")
X_seq_length = tf.placeholder(tf.int32, [None], name="X_seq_length")

g_data = gan.generator(noise=noise, batch_size=batch_size, n_outputs=g_n_outputs, 
                       max_seq_length=max_policy_history_length, seq_length=noise_seq_length)

# # Let's make sure the initial value at [:, 0, 1] is 0 (current capital at policy inception)
# flat = tf.reshape(tensor=g_data, shape=[batch_size * max_policy_history_length * g_n_outputs])
# flat2 = tf.Variable(initial_value=tf.zeros_like(flat), trainable=False, name="xyFlat")
# flat3 = tf.assign(ref=flat2, value=flat)
# flat4 = tf.scatter_update(flat3, [1 + i * max_policy_history_length * g_n_outputs for i in range(batch_size)],
#                                  [0 for j in range(batch_size)])
# g_ms_data = tf.reshape(tensor=flat4, shape=[batch_size, max_policy_history_length, g_n_outputs])

logits_d_for_X, y_pred_X = gan.discriminator(X=X, seq_length=X_seq_length, n_outputs=d_n_outputs)
logits_d_for_g, y_pred_g = gan.discriminator(X=g_data, seq_length=noise_seq_length, n_outputs=d_n_outputs, reuse=True)

g_loss, accuracy_g = gan.generator_loss(batch_size=batch_size, logits_d=logits_d_for_g)
d_loss_real, accuracy_d_real = gan.discriminator_loss_real(logits=logits_d_for_X, y=y)
d_loss_fake, accuracy_d_fake = gan.discriminator_loss_fake(batch_size=batch_size, logits=logits_d_for_g)

g_trainer = gan.generator_trainer(g_learning_rate, g_loss)
d_trainer_real = gan.discriminator_trainer_real(d_real_learning_rate, d_loss_real + d_loss_fake)
#d_trainer_fake = gan.discriminator_trainer_fake(d_fake_learning_rate, d_loss_fake)

tf.summary.scalar('Generator_loss', g_loss)
tf.summary.scalar('Discriminator_loss_real', d_loss_real)
tf.summary.scalar('Discriminator_loss_fake', d_loss_fake)

merged = tf.summary.merge_all()
writer = tf.summary.FileWriter(log_dir, tf.get_default_graph())

tvars = tf.trainable_variables()

d_saver = tf.train.Saver(var_list=[var for var in tvars if "t_discriminator" in var.name])
g_saver = tf.train.Saver(var_list=[var for var in tvars if "t_generator" in var.name])

In [3]:
import numpy as np

np.set_printoptions(formatter={'float_kind': (lambda x: "%.2f" % x)})

sess = tf.Session()

sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

# n_epochs = 100
# 
# # Pre-train discriminator
# for epoch in range(n_epochs):
#     for batch in range(train_data.num_examples // batch_size):
#         noise_batch = np.random.normal(0, 1, size=[batch_size, max_policy_history_length, noise_dimensions])
#         noise_seq_length_batch = np.full(batch_size, max_policy_history_length)
# 
#         y_batch, X_batch, X_seq_length_batch = train_data.next_batch(batch_size)
# 
#         _, dLossReal, dLossFake, acc_real_train, acc_fake_train = \
#             sess.run([d_trainer_real, d_loss_real, d_loss_fake, accuracy_d_real, accuracy_d_fake],
#                      {X: X_batch, y: y_batch, X_seq_length: X_seq_length_batch,
#                       noise: noise_batch, noise_seq_length: noise_seq_length_batch})
# 
#     print("Epoch:", epoch, "dLossReal:", dLossReal, "acc_real_train:", acc_real_train,
#           "dLossFake:", dLossFake, "acc_fake_train:", acc_fake_train)
# 
# d_saver.save(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "discriminator.ckpt"))

In [5]:
d_saver.restore(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "discriminator.ckpt"))
#g_saver.restore(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "generator.ckpt"))

#Train generator and discriminator together
n_epochs = 200

for epoch in range(n_epochs):
    for batch in range(train_data.num_examples // batch_size):
        noise_batch = np.random.normal(1250, 5, size=[batch_size, max_policy_history_length, noise_dimensions])
        noise_batch[:, 0, 1] = 0
        noise_seq_length_batch = np.full(batch_size, max_policy_history_length)
        
        y_batch, X_batch, X_seq_length_batch = train_data.next_batch(batch_size)

        # Train discriminator on both real and fake data
        _, dLossReal, dLossFake, acc_real_train, acc_fake_train = \
            sess.run([d_trainer_real, d_loss_real, d_loss_fake, accuracy_d_real, accuracy_d_fake],
                     {X: X_batch, y: y_batch, X_seq_length: X_seq_length_batch,
                      noise: noise_batch, noise_seq_length: noise_seq_length_batch})

        # Train generator    
        _, dLossFake, acc_d_fake, gLoss, acc_g, gData = sess.run([g_trainer, d_loss_fake, accuracy_d_fake,
                                                                         g_loss, accuracy_g, g_data],
                                          feed_dict={noise: noise_batch, noise_seq_length: noise_seq_length_batch})

    print("Epoch:", epoch, 
          "dLossFake:", dLossFake, "acc_fake_train:", acc_d_fake,
          "gLoss:", gLoss, "acc_g:", acc_g)

    print(gData[0])


INFO:tensorflow:Restoring parameters from /Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife/model_checkpoints/discriminator.ckpt


Epoch: 0 dLossFake: 0.17438 acc_fake_train: 1.0 gLoss: 1.83245 acc_g: 0.0
[[65.65 118.47]
 [111.03 302.92]
 [41.70 233.71]
 [67.19 135.30]
 [59.82 97.27]
 [27.55 65.47]
 [20.22 52.06]
 [19.23 51.36]
 [18.18 51.21]
 [16.75 49.42]
 [15.55 47.00]
 [14.50 45.50]
 [13.73 44.19]
 [13.12 43.12]
 [12.66 41.79]]


Epoch: 1 dLossFake: 0.268625 acc_fake_train: 1.0 gLoss: 1.44576 acc_g: 0.0
[[4.44 2.27]
 [4.84 4.45]
 [4.09 8.43]
 [5.05 9.05]
 [5.32 9.85]
 [4.49 10.91]
 [4.60 11.66]
 [3.85 10.75]
 [4.03 11.80]
 [3.97 11.76]
 [3.96 11.77]
 [3.95 11.66]
 [3.88 11.57]
 [3.92 11.70]
 [3.91 11.71]]


Epoch: 2 dLossFake: 0.0518422 acc_fake_train: 1.0 gLoss: 2.98573 acc_g: 0.0
[[4.48 4.01]
 [4.14 5.54]
 [4.43 6.33]
 [7.41 11.57]
 [5.67 12.34]
 [6.84 14.56]
 [9.52 15.13]
 [10.38 18.76]
 [8.00 21.14]
 [7.13 26.44]
 [7.72 32.88]
 [8.87 39.03]
 [9.42 38.11]
 [8.44 33.10]
 [7.06 29.39]]


Epoch: 3 dLossFake: 0.602505 acc_fake_train: 1.0 gLoss: 0.792848 acc_g: 0.0
[[13.74 20.41]
 [18.93 27.08]
 [16.41 24.08]
 [17.25 14.64]
 [10.59 33.85]
 [19.96 39.88]
 [22.20 47.11]
 [28.74 71.21]
 [9.30 88.34]
 [25.48 73.33]
 [20.96 89.79]
 [33.41 107.17]
 [-4.10 11.41]
 [-4.97 -6.71]
 [-1.15 -3.97]]


Epoch: 4 dLossFake: 0.176063 acc_fake_train: 1.0 gLoss: 1.8238 acc_g: 0.0
[[38.83 66.82]
 [42.46 79.73]
 [43.51 82.48]
 [118.78 204.91]
 [67.01 169.78]
 [57.35 132.66]
 [53.20 98.30]
 [54.01 210.89]
 [71.96 211.13]
 [59.10 222.96]
 [65.41 240.68]
 [53.19 260.35]
 [6.83 4.02]
 [7.63 29.45]
 [1.01 5.39]]


Epoch: 5 dLossFake: 0.668123 acc_fake_train: 1.0 gLoss: 0.718818 acc_g: 0.0
[[140.06 108.89]
 [123.80 158.18]
 [76.34 160.53]
 [148.65 258.45]
 [109.49 256.18]
 [146.57 359.34]
 [190.79 406.03]
 [237.36 640.24]
 [160.16 617.57]
 [190.43 801.96]
 [177.06 832.53]
 [144.46 876.21]
 [-26.61 26.25]
 [16.05 18.59]
 [13.41 30.86]]


Epoch: 6 dLossFake: 0.26438 acc_fake_train: 1.0 gLoss: 1.45965 acc_g: 0.0
[[165.55 27.86]
 [130.05 108.67]
 [93.81 153.17]
 [112.97 172.17]
 [113.78 237.09]
 [121.35 335.56]
 [122.45 332.13]
 [120.90 374.52]
 [131.32 490.06]
 [119.57 475.83]
 [129.36 607.25]
 [135.16 626.59]
 [1.72 19.24]
 [2.87 4.26]
 [1.50 1.63]]


Epoch: 7 dLossFake: 0.234922 acc_fake_train: 1.0 gLoss: 1.56367 acc_g: 0.0
[[128.70 53.98]
 [149.45 112.20]
 [143.89 202.44]
 [180.12 241.70]
 [189.38 341.32]
 [176.02 372.99]
 [163.56 482.03]
 [157.70 482.15]
 [157.59 672.57]
 [144.35 659.72]
 [150.60 768.29]
 [168.23 836.59]
 [6.27 6.66]
 [1.60 7.51]
 [3.95 13.25]]


Epoch: 8 dLossFake: 0.28144 acc_fake_train: 1.0 gLoss: 1.40526 acc_g: 0.0
[[121.58 30.52]
 [110.20 68.48]
 [108.14 130.66]
 [117.48 171.09]
 [133.62 222.04]
 [110.80 323.01]
 [98.35 362.70]
 [133.73 428.39]
 [155.05 482.95]
 [139.30 500.12]
 [161.27 650.55]
 [102.02 657.77]
 [2.92 -3.67]
 [-4.99 1.30]
 [-1.97 -3.45]]


Epoch: 9 dLossFake: 0.00948589 acc_fake_train: 1.0 gLoss: 4.66273 acc_g: 0.0
[[72.75 59.77]
 [148.99 166.90]
 [136.63 259.34]
 [192.82 303.73]
 [220.93 383.43]
 [244.25 501.32]
 [225.49 571.79]
 [226.29 608.94]
 [247.00 800.83]
 [230.14 809.75]
 [199.42 1039.39]
 [189.59 1086.80]
 [0.28 0.11]
 [0.80 -8.88]
 [-10.56 -17.58]]


Epoch: 10 dLossFake: 0.169909 acc_fake_train: 1.0 gLoss: 1.85632 acc_g: 0.0
[[152.28 12.77]
 [114.92 110.41]
 [87.32 136.51]
 [91.76 191.02]
 [96.54 205.60]
 [100.10 294.89]
 [89.74 306.85]
 [81.66 387.98]
 [87.28 367.17]
 [91.46 490.10]
 [115.68 477.86]
 [104.52 495.52]
 [0.28 0.08]
 [0.44 0.36]
 [0.29 0.42]]


Epoch: 11 dLossFake: 0.310806 acc_fake_train: 1.0 gLoss: 1.31997 acc_g: 0.0
[[110.96 -1.95]
 [102.99 106.06]
 [95.59 119.24]
 [108.17 228.71]
 [112.75 244.93]
 [121.31 330.64]
 [96.50 322.20]
 [104.77 432.48]
 [107.09 468.01]
 [107.94 571.72]
 [127.95 557.79]
 [124.16 576.91]
 [0.28 0.02]
 [-0.07 -0.03]
 [-1.39 -0.52]]


Epoch: 12 dLossFake: 0.0804361 acc_fake_train: 1.0 gLoss: 2.56025 acc_g: 0.0
[[131.22 16.29]
 [130.33 124.55]
 [144.98 152.20]
 [137.01 287.37]
 [143.82 318.01]
 [142.26 430.31]
 [134.82 451.95]
 [137.03 585.40]
 [143.01 637.48]
 [144.60 778.99]
 [176.07 794.97]
 [178.10 822.27]
 [0.28 -0.02]
 [-0.21 -0.22]
 [-1.14 -0.61]]


Epoch: 13 dLossFake: 0.233637 acc_fake_train: 1.0 gLoss: 1.56853 acc_g: 0.0
[[100.21 5.32]
 [96.26 95.03]
 [97.31 110.26]
 [91.61 196.89]
 [90.06 212.31]
 [100.10 295.97]
 [85.57 296.25]
 [84.06 376.84]
 [86.96 396.17]
 [84.83 475.88]
 [112.93 473.99]
 [109.53 500.55]
 [0.29 -0.05]
 [-0.14 -0.32]
 [0.12 -0.03]]


Epoch: 14 dLossFake: 0.171721 acc_fake_train: 1.0 gLoss: 1.84655 acc_g: 0.0
[[172.33 -10.59]
 [165.54 172.65]
 [171.31 173.04]
 [150.67 345.18]
 [159.83 335.82]
 [159.36 489.67]
 [153.70 509.00]
 [148.70 639.03]
 [149.58 652.54]
 [158.09 840.56]
 [202.57 844.88]
 [205.78 895.81]
 [1.39 3.17]
 [0.70 2.52]
 [0.52 0.27]]


Epoch: 15 dLossFake: 0.201768 acc_fake_train: 1.0 gLoss: 1.69983 acc_g: 0.0
[[186.70 2.32]
 [177.39 183.81]
 [174.51 169.26]
 [170.16 338.74]
 [176.63 361.63]
 [176.20 539.48]
 [174.43 576.04]
 [173.34 747.89]
 [173.64 771.47]
 [165.98 918.01]
 [217.26 914.41]
 [185.52 943.06]
 [0.29 -0.14]
 [2.58 -1.65]
 [-5.96 -6.04]]


Epoch: 16 dLossFake: 0.267545 acc_fake_train: 1.0 gLoss: 1.44932 acc_g: 0.0
[[143.75 8.76]
 [113.62 138.38]
 [104.03 110.41]
 [88.84 182.60]
 [96.13 179.23]
 [78.40 215.36]
 [78.81 227.30]
 [75.60 253.15]
 [72.30 250.61]
 [61.97 236.04]
 [63.64 310.18]
 [66.52 294.51]
 [0.30 -0.19]
 [-0.36 -0.92]
 [0.89 -1.14]]


Epoch: 17 dLossFake: 0.392698 acc_fake_train: 1.0 gLoss: 1.12473 acc_g: 0.0
[[135.71 65.80]
 [129.47 138.70]
 [158.58 174.87]
 [177.74 284.36]
 [186.48 334.19]
 [155.25 370.37]
 [158.64 397.75]
 [154.35 536.06]
 [168.13 623.21]
 [157.52 604.82]
 [171.47 692.38]
 [130.47 753.05]
 [0.30 -0.20]
 [-0.20 -0.76]
 [0.80 -0.22]]


Epoch: 18 dLossFake: 0.152975 acc_fake_train: 1.0 gLoss: 1.953 acc_g: 0.0
[[59.44 26.22]
 [48.16 47.22]
 [41.80 59.43]
 [50.13 81.62]
 [61.25 101.60]
 [59.09 141.68]
 [50.55 160.06]
 [41.92 208.14]
 [54.02 234.13]
 [68.58 264.12]
 [68.72 296.42]
 [76.04 306.87]
 [0.30 -0.22]
 [2.31 2.36]
 [1.61 0.30]]


Epoch: 19 dLossFake: 0.0775605 acc_fake_train: 1.0 gLoss: 2.59523 acc_g: 0.0
[[154.57 25.22]
 [180.32 140.16]
 [196.71 185.35]
 [209.85 285.42]
 [195.05 378.53]
 [179.09 466.85]
 [178.41 536.16]
 [185.81 566.15]
 [215.66 803.26]
 [221.37 795.92]
 [166.29 984.79]
 [239.60 1016.71]
 [0.31 -0.29]
 [-0.18 -0.87]
 [-0.02 1.04]]


Epoch: 20 dLossFake: 0.101597 acc_fake_train: 1.0 gLoss: 2.33714 acc_g: 0.0
[[239.51 55.43]
 [187.88 207.34]
 [169.39 208.54]
 [163.34 335.09]
 [218.17 293.07]
 [176.11 534.87]
 [160.45 584.88]
 [191.23 727.67]
 [187.81 746.26]
 [194.29 791.78]
 [206.26 908.20]
 [185.78 957.50]
 [9.53 16.20]
 [2.17 -5.62]
 [-7.95 -23.57]]


Epoch: 21 dLossFake: 0.497554 acc_fake_train: 1.0 gLoss: 0.936597 acc_g: 0.0
[[189.16 -2.73]
 [130.42 145.96]
 [195.37 141.66]
 [231.59 372.70]
 [251.97 450.48]
 [222.13 596.13]
 [270.88 708.23]
 [315.44 759.48]
 [287.21 1012.83]
 [283.07 1106.17]
 [254.70 1264.20]
 [290.54 1282.85]
 [-0.40 -2.94]
 [1.99 2.09]
 [6.28 11.11]]


Epoch: 22 dLossFake: 0.430936 acc_fake_train: 1.0 gLoss: 1.04955 acc_g: 0.0
[[75.16 38.60]
 [43.89 43.48]
 [43.63 56.38]
 [44.18 70.30]
 [46.76 59.46]
 [36.69 88.77]
 [32.57 88.07]
 [23.62 109.25]
 [33.92 134.93]
 [59.78 204.77]
 [46.28 184.02]
 [16.55 43.89]
 [2.85 4.79]
 [1.43 4.37]
 [1.26 5.06]]


Epoch: 23 dLossFake: 0.0134659 acc_fake_train: 1.0 gLoss: 4.31438 acc_g: 0.0
[[82.25 33.19]
 [74.51 72.15]
 [89.02 123.81]
 [34.68 74.03]
 [112.15 178.62]
 [54.42 121.71]
 [73.24 129.93]
 [64.83 168.89]
 [62.46 193.98]
 [63.96 217.61]
 [51.03 217.31]
 [50.94 205.67]
 [42.13 186.69]
 [43.66 168.68]
 [43.17 155.65]]


Epoch: 24 dLossFake: 0.0999133 acc_fake_train: 1.0 gLoss: 2.35304 acc_g: 0.0
[[36.89 52.68]
 [113.47 86.79]
 [114.36 93.19]
 [70.08 61.89]
 [1.80 50.37]
 [34.97 51.52]
 [26.06 34.49]
 [25.43 44.23]
 [22.48 49.66]
 [23.93 56.39]
 [20.67 60.76]
 [21.08 68.67]
 [20.90 69.75]
 [20.99 71.39]
 [20.59 71.81]]


Epoch: 25 dLossFake: 0.115003 acc_fake_train: 1.0 gLoss: 2.21978 acc_g: 0.0
[[26.15 30.69]
 [24.05 14.12]
 [19.55 24.08]
 [13.99 16.26]
 [3.82 23.33]
 [22.68 19.66]
 [16.35 22.47]
 [14.66 32.37]
 [15.92 32.00]
 [12.92 33.31]
 [11.91 37.73]
 [14.02 50.20]
 [14.76 51.78]
 [14.94 54.59]
 [14.93 54.84]]


Epoch: 26 dLossFake: 0.0863275 acc_fake_train: 1.0 gLoss: 2.49248 acc_g: 0.0
[[13.53 13.30]
 [15.46 9.34]
 [13.56 18.85]
 [11.34 15.75]
 [3.05 20.57]
 [20.11 20.06]
 [15.47 26.08]
 [13.97 34.71]
 [14.57 34.35]
 [14.65 36.02]
 [13.57 41.81]
 [17.31 55.89]
 [18.85 60.68]
 [21.21 69.86]
 [22.01 72.44]]


Epoch: 27 dLossFake: 0.0317003 acc_fake_train: 1.0 gLoss: 3.46728 acc_g: 0.0
[[10.30 7.00]
 [11.32 6.93]
 [12.84 15.91]
 [10.46 16.38]
 [5.79 21.62]
 [18.18 20.02]
 [15.83 24.28]
 [11.86 33.04]
 [12.90 34.93]
 [14.33 36.95]
 [12.69 42.77]
 [15.83 52.90]
 [18.24 59.99]
 [20.84 66.37]
 [21.73 68.28]]


Epoch: 28 dLossFake: 0.0592816 acc_fake_train: 1.0 gLoss: 2.85495 acc_g: 0.0
[[11.81 6.60]
 [13.75 8.84]
 [11.98 18.41]
 [12.46 19.32]
 [9.11 23.01]
 [20.63 30.44]
 [19.10 32.61]
 [15.95 45.42]
 [17.58 43.50]
 [20.02 49.05]
 [16.91 59.41]
 [18.08 67.83]
 [24.18 81.25]
 [29.68 92.25]
 [29.57 89.61]]


Epoch: 29 dLossFake: 0.0151279 acc_fake_train: 1.0 gLoss: 4.19877 acc_g: 0.0
[[14.21 7.08]
 [18.87 10.77]
 [17.91 25.34]
 [18.76 21.40]
 [16.37 34.13]
 [26.69 37.66]
 [23.87 48.15]
 [23.46 60.75]
 [27.33 62.57]
 [30.09 69.74]
 [24.28 86.23]
 [27.42 97.44]
 [39.63 119.94]
 [43.83 136.65]
 [43.02 135.15]]


Epoch: 30 dLossFake: 0.0956039 acc_fake_train: 1.0 gLoss: 2.39497 acc_g: 0.0
[[11.12 5.04]
 [20.01 7.09]
 [16.16 21.07]
 [18.78 21.83]
 [19.28 33.42]
 [26.97 39.63]
 [29.95 50.57]
 [27.99 72.27]
 [31.07 74.64]
 [34.45 85.79]
 [30.77 107.18]
 [36.60 120.40]
 [51.06 151.71]
 [57.22 174.00]
 [58.12 180.33]]


Epoch: 31 dLossFake: 0.0881288 acc_fake_train: 1.0 gLoss: 2.47271 acc_g: 0.0
[[16.63 6.91]
 [31.27 7.08]
 [23.83 29.02]
 [30.73 28.48]
 [26.56 50.95]
 [34.62 66.37]
 [42.25 70.75]
 [43.84 104.67]
 [39.50 106.49]
 [48.76 117.36]
 [46.59 150.42]
 [49.53 162.73]
 [65.67 200.33]
 [71.20 225.06]
 [72.51 236.29]]


Epoch: 32 dLossFake: 0.0121928 acc_fake_train: 1.0 gLoss: 4.41301 acc_g: 0.0
[[18.32 9.05]
 [23.06 15.82]
 [19.22 30.17]
 [28.23 33.57]
 [24.73 55.33]
 [29.27 59.46]
 [31.65 68.44]
 [30.20 77.19]
 [36.65 86.91]
 [32.88 84.32]
 [29.40 110.37]
 [36.14 115.07]
 [41.67 117.20]
 [33.08 148.37]
 [36.72 149.19]]


KeyboardInterrupt: 

In [5]:
g_saver.save(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "generator.ckpt"))

'/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife/model_checkpoints/generator.ckpt'