In [1]:
import os
from datetime import datetime

#PROJECT_ROOT_DIR = "/home/ubuntu/TroubledLife"
PROJECT_ROOT_DIR = "/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife"
TF_LOG_DIR = os.path.join(PROJECT_ROOT_DIR, "tf_logs")
MODEL_CHECKPOINTS_DIR = os.path.join(PROJECT_ROOT_DIR, "model_checkpoints")

now = datetime.now().strftime("%Y%m%d-%H%M%S")
log_dir = "{}/run-{}/".format(TF_LOG_DIR, now)


import data_preparation as dp

runtime = 5


def generator_loss(Gz, init_z):
    premium = init_z[:, 0]
    interest = init_z[:, 1] * 0.03 + init_z[:, 2] * 0.04 + init_z[:, 3] * 0.05 + init_z[:, 4] * 0.06
    
    k1 = premium
    k1v = k1 * (1 + interest)
    k2 = premium + k1v
    k2v = k2 * (1 + interest)
    k3 = premium + k2v
    k3v = k3 * (1 + interest)
    k4 = premium + k3v
    k4v = k4 * (1 + interest)
    k5 = premium + k4v
    k5v = k5 * (1 + interest)
    
    # loss = (tf.abs(Gz[:, 0, 0] - premium) + tf.abs(Gz[:, 0, 1]) +
    #                        tf.abs(Gz[:, 1, 0] - premium) + tf.abs(Gz[:, 1, 1] - k1) +
    #                        tf.abs(Gz[:, 2, 0] - premium) + tf.abs(Gz[:, 2, 1] - k1v) +
    #                        tf.abs(Gz[:, 3, 0] - premium) + tf.abs(Gz[:, 3, 1] - k2) +
    #                        tf.abs(Gz[:, 4, 0] - premium) + tf.abs(Gz[:, 4, 1] - k2v) +
    #                        tf.abs(Gz[:, 5, 0] - premium) + tf.abs(Gz[:, 5, 1] - k3) +
    #                        tf.abs(Gz[:, 6, 0] - premium) + tf.abs(Gz[:, 6, 1] - k3v) +
    #                        tf.abs(Gz[:, 7, 0] - premium) + tf.abs(Gz[:, 7, 1] - k4) +
    #                        tf.abs(Gz[:, 8, 0] - premium) + tf.abs(Gz[:, 8, 1] - k4v) +
    #                        tf.abs(Gz[:, 9, 0] - premium) + tf.abs(Gz[:, 9, 1] - k5) +
    #                        tf.abs(Gz[:, 10, 0] - premium) + tf.abs(Gz[:, 10, 1] - k5v)
    #                        )
    
    boost = 1

    loss = (tf.pow(boost * (Gz[:, 0, 0] - premium), 2) + tf.pow(Gz[:, 0, 1], 2) +
                           tf.pow(boost * (Gz[:, 1, 0] - premium), 2) + tf.pow(boost * (Gz[:, 1, 1] - k1), 2) +
                           tf.pow(boost * (Gz[:, 2, 0] - premium), 2) + tf.pow(boost * (Gz[:, 2, 1] - k1v), 2) +
                           tf.pow(boost * (Gz[:, 3, 0] - premium), 2) + tf.pow(boost * (Gz[:, 3, 1] - k2), 2) +
                           tf.pow(boost * (Gz[:, 4, 0] - premium), 2) + tf.pow(boost * (Gz[:, 4, 1] - k2v), 2) +
                           tf.pow(boost * (Gz[:, 5, 0] - premium), 2) + tf.pow(boost * (Gz[:, 5, 1] - k3), 2) +
                           tf.pow(boost * (Gz[:, 6, 0] - premium), 2) + tf.pow(boost * (Gz[:, 6, 1] - k3v), 2) +
                           tf.pow(boost * (Gz[:, 7, 0] - premium), 2) + tf.pow(boost * (Gz[:, 7, 1] - k4), 2) +
                           tf.pow(boost * (Gz[:, 8, 0] - premium), 2) + tf.pow(boost * (Gz[:, 8, 1] - k4v), 2) +
                           tf.pow(boost * (Gz[:, 9, 0] - premium), 2) + tf.pow(boost * (Gz[:, 9, 1] - k5), 2) +
                           tf.pow(boost * (Gz[:, 10, 0] - premium), 2) + tf.pow(boost * (Gz[:, 10, 1] - k5v), 2)
                           )
    loss_mean = tf.reduce_mean(loss) + tf.reduce_mean(tf.abs(tf.abs(1250 - premium) - 250))
                           
    # loss_mean = tf.reduce_mean(tf.abs(Gz[:, 0, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 0, 1])) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 1, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 1, 1] - k1)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 2, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 2, 1] - k1v)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 3, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 3, 1] - k2)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 4, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 4, 1] - k2v)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 5, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 5, 1] - k3)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 6, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 6, 1] - k3v)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 7, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 7, 1] - k4)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 8, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 8, 1] - k4v)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 9, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 9, 1] - k5)) + \
    #             tf.reduce_mean(tf.abs(Gz[:, 10, 0] - premium)) + tf.reduce_mean(tf.abs(Gz[:, 10, 1] - k5v))

    #loss_mean = tf.reduce_mean(loss)
    
    return loss_mean, loss

def numpy_correct(init_z, gData):
    correct = np.full(shape=(size_batch, max_length_policy_history, 2), fill_value=0.0)
    
    premium = init_z[:, 0]
    interest = init_z[:, 1] * 0.03 + init_z[:, 2] * 0.04 + init_z[:, 3] * 0.05 + init_z[:, 4] * 0.06

    k1 = premium
    k1v = k1 * (1 + interest)
    k2 = premium + k1v
    k2v = k2 * (1 + interest)
    k3 = premium + k2v
    k3v = k3 * (1 + interest)
    k4 = premium + k3v
    k4v = k4 * (1 + interest)
    k5 = premium + k4v
    k5v = k5 * (1 + interest)
    
    correct[:, 0, 0] = premium
    correct[:, 0, 1] = 0.0
    correct[:, 1, 0] = premium
    correct[:, 1, 1] = k1
    correct[:, 2, 0] = premium
    correct[:, 2, 1] = k1v
    correct[:, 3, 0] = premium
    correct[:, 3, 1] = k2
    correct[:, 4, 0] = premium
    correct[:, 4, 1] = k2v
    correct[:, 5, 0] = premium
    correct[:, 5, 1] = k3
    correct[:, 6, 0] = premium
    correct[:, 6, 1] = k3v
    correct[:, 7, 0] = premium
    correct[:, 7, 1] = k4
    correct[:, 8, 0] = premium
    correct[:, 8, 1] = k4v
    correct[:, 9, 0] = premium
    correct[:, 9, 1] = k5
    correct[:, 10, 0] = premium
    correct[:, 10, 1] = k5v
 
    np_loss = (np.fabs(gData[:, 0, 0] - premium) + np.fabs(gData[:, 0, 1]) +
                           np.fabs(gData[:, 1, 0] - premium) + np.fabs(gData[:, 1, 1] - k1) +
                           np.fabs(gData[:, 2, 0] - premium) + np.fabs(gData[:, 2, 1] - k1v) +
                           np.fabs(gData[:, 3, 0] - premium) + np.fabs(gData[:, 3, 1] - k2) +
                           np.fabs(gData[:, 4, 0] - premium) + np.fabs(gData[:, 4, 1] - k2v) +
                           np.fabs(gData[:, 5, 0] - premium) + np.fabs(gData[:, 5, 1] - k3) +
                           np.fabs(gData[:, 6, 0] - premium) + np.fabs(gData[:, 6, 1] - k3v) +
                           np.fabs(gData[:, 7, 0] - premium) + np.fabs(gData[:, 7, 1] - k4) +
                           np.fabs(gData[:, 8, 0] - premium) + np.fabs(gData[:, 8, 1] - k4v) +
                           np.fabs(gData[:, 9, 0] - premium) + np.fabs(gData[:, 9, 1] - k5) +
                           np.fabs(gData[:, 10, 0] - premium) + np.fabs(gData[:, 10, 1] - k5v)
                           )
   
    return np_loss


In [2]:
import tensorflow as tf
import gan as gan

size_batch = 200
max_length_policy_history=15

# Generator hyperparameters
gru_g=False
leaky_g=False
n_inputs_g = 5
n_layers_g = 3
n_neurons_g = 100
n_outputs_g = 2
input_keep_prob_g = 0.9
learning_rate_g = 1e-7
beta1_g=0.99
beta2_g=0.999
epsilon_g=1e-08
clip_g=True
threshold_g = 1.0

tf.reset_default_graph()
tf.set_random_seed(42)

Z = tf.placeholder(tf.float64, [None, max_length_policy_history, n_inputs_g], name='Z')
init_z = tf.placeholder(tf.float64, [None, n_inputs_g], name='init_z')
seq_length_z = tf.placeholder(tf.int64, [None], name='seq_length_z')

Gz = gan.generator(Z=Z, n_outputs=n_outputs_g, seq_length_max=max_length_policy_history,
                   n_layers=n_layers_g, n_neurons=n_neurons_g, 
                   seq_length=seq_length_z, gru=gru_g, leaky=leaky_g, input_keep_prob=input_keep_prob_g)

loss_mean_g, loss_g = generator_loss(Gz=Gz, init_z=init_z)

g_trainer = gan.generator_trainer(learning_rate=learning_rate_g, beta1=beta1_g, beta2=beta2_g, epsilon=epsilon_g, 
                                  clip=clip_g, threshold=threshold_g, loss=loss_mean_g)

tf.summary.scalar('Generator_loss', loss_mean_g)

merged = tf.summary.merge_all()
writer = tf.summary.FileWriter(log_dir, tf.get_default_graph())

tvars = tf.trainable_variables()

g_saver = tf.train.Saver(var_list=[var for var in tvars if "t_generator" in var.name])

Tensor("t_generator/rnn/transpose:0", shape=(?, 15, 100), dtype=float64)
(<tf.Tensor 't_generator/rnn/while/Exit_2:0' shape=(?, 100) dtype=float64>, <tf.Tensor 't_generator/rnn/while/Exit_3:0' shape=(?, 100) dtype=float64>, <tf.Tensor 't_generator/rnn/while/Exit_4:0' shape=(?, 100) dtype=float64>)
Tensor("t_generator/dense/BiasAdd:0", shape=(?, 15, 2), dtype=float64)


In [29]:
import numpy as np

np.set_printoptions(formatter={'float_kind': (lambda x: "%.2f" % x)})

sess = tf.Session()

sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

In [30]:
g_saver.restore(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "generator.ckpt"))

n_epochs = 400
num_examples = 10000

for epoch in range(n_epochs):
    for batch in range(num_examples // size_batch):
        Z_batch, seq_length_z_batch, init_z_batch = dp.generate_Z_batch(
            size_batch=size_batch, max_length_policy_history=max_length_policy_history, 
            n_inputs = n_inputs_g, runtime=runtime)

        _, lossMeanG, lossG, gData = \
            sess.run([g_trainer, loss_mean_g, loss_g, Gz], 
                     feed_dict={Z: Z_batch, seq_length_z: seq_length_z_batch, init_z: init_z_batch})

    summary = sess.run(merged, feed_dict={Z: Z_batch, seq_length_z: seq_length_z_batch, init_z: init_z_batch})
    writer.add_summary(summary, epoch)

    print("Epoch:", epoch, "lossG:", lossMeanG)
    
    np_loss = numpy_correct(init_z=init_z_batch, gData=gData)
    print(lossG[0])
    #print(np_loss[0])
    print(Z_batch[0, 0])
    print(gData[0])
    
g_saver.save(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "generator3.ckpt"))    

INFO:tensorflow:Restoring parameters from /Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife/model_checkpoints/generator.ckpt


Epoch: 0 lossG: 26996344.3541
3247845.2668
[1112.15 0.00 0.00 1.00 0.00]
[[1194.12 -5.28]
 [1289.39 1326.48]
 [1457.62 1402.73]
 [1208.52 2692.67]
 [916.37 2952.19]
 [1163.62 4002.72]
 [1363.91 4263.80]
 [1072.60 5307.65]
 [1404.10 5835.40]
 [1060.23 6416.96]
 [1419.54 7253.84]
 [0.02 0.01]
 [0.02 0.01]
 [0.02 0.01]
 [0.02 0.01]]


Epoch: 1 lossG: 28089604.7694
2953689.63995
[1305.50 0.00 0.00 1.00 0.00]
[[1317.88 -37.87]
 [1571.04 1386.81]
 [1579.62 1497.43]
 [1451.07 2879.77]
 [1510.80 3257.36]
 [1210.56 4507.66]
 [1519.54 4564.14]
 [1739.62 5885.48]
 [1720.21 6232.85]
 [1916.10 7686.62]
 [1840.32 8466.70]
 [0.02 0.01]
 [0.02 0.01]
 [0.02 0.01]
 [0.02 0.01]]


Epoch: 2 lossG: 23389055.235
3753553.86075
[1208.56 0.00 0.00 1.00 0.00]
[[1358.73 -58.02]
 [1427.37 1281.58]
 [1583.47 1541.59]
 [1385.51 2779.08]
 [1299.60 3117.14]
 [1343.79 4364.69]
 [1293.49 4382.65]
 [1294.40 5945.96]
 [1051.97 6386.60]
 [1246.98 7332.95]
 [1453.22 7835.00]
 [0.02 0.01]
 [0.02 0.01]
 [0.02 0.01]
 [0.02 0.01]]


Epoch: 3 lossG: 29800949.1984
5562811.55759
[1269.83 0.00 1.00 0.00 0.00]
[[1497.68 -56.40]
 [1445.12 1564.78]
 [1293.67 1644.93]
 [1461.83 2885.98]
 [1448.54 3318.98]
 [1205.38 4825.19]
 [1496.25 4803.26]
 [1261.63 6439.32]
 [1332.95 6666.83]
 [1668.18 6597.22]
 [1742.69 8044.27]
 [0.02 0.01]
 [0.02 0.01]
 [0.02 0.01]
 [0.02 0.01]]


KeyboardInterrupt: 

In [20]:
g_saver.save(sess, os.path.join(MODEL_CHECKPOINTS_DIR, "generator.ckpt"))

 

'/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife/model_checkpoints/generator.ckpt'