Generate, load and prepare policy histories

In [1]:
import os
from datetime import datetime
import support_functions as sf


PROJECT_ROOT_DIR = "/Users/gopora/MyStuff/Dev/Workspaces/Sandbox/TroubledLife"
DATASETS_DIR = os.path.join(PROJECT_ROOT_DIR, "data")
TF_LOG_DIR = os.path.join(PROJECT_ROOT_DIR, "tf_logs")
TRAINING_SET_DATA_FILE = "troubled_life_policy_train_data.csv"
TEST_SET_DATA_FILE = "troubled_life_policy_test_data.csv"

now = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
log_dir = "{}/run-{}/".format(TF_LOG_DIR, now)

In [2]:
#sf.generate_troubled_life_policy_data(no_of_policies=10000, runtime=5, file_path=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))

#sf.generate_troubled_life_policy_data(no_of_policies=2000, runtime=5, file_path=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

policy_histories_train = \
    sf.load_troubled_life_policy_data(file_path=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))

policy_histories_test = \
    sf.load_troubled_life_policy_data(file_path=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

policy_histories_length_train, max_policy_history_length_train = \
    sf.get_policy_history_lengths(policy_histories=policy_histories_train)

policy_histories_length_test, max_policy_history_length_test = \
    sf.get_policy_history_lengths(policy_histories=policy_histories_test)

max_policy_history_length = max(max_policy_history_length_train, max_policy_history_length_test)

In [3]:
# Pad the histories up to maximum length of both, train and test set

# policy_histories_train = \
#     sf.pad_troubled_life_policy_histories(policy_histories=policy_histories_train,
#                                           policy_histories_lengths=policy_histories_length_train,
#                                           max_policy_history_length=max_policy_history_length)

# policy_histories_test = \
#     sf.pad_troubled_life_policy_histories(policy_histories=policy_histories_test,
#                                           policy_histories_lengths=policy_histories_length_test,
#                                           max_policy_history_length=max_policy_history_length)

# Save padded data, since always generating and padding takes too long
#policy_histories_train.to_csv(path_or_buf=os.path.join(DATASETS_DIR, TRAINING_SET_DATA_FILE))
#policy_histories_test.to_csv(path_or_buf=os.path.join(DATASETS_DIR, TEST_SET_DATA_FILE))

Prepare labels and features

In [4]:
# Extract features and labels from dataset as numpy.ndarray(s)
train_labels, train_features, train_seq_lengths =\
    sf.prepare_labels_features_lengths(policy_histories=policy_histories_train,
                                       policy_histories_lengths=policy_histories_length_train, 
                                       max_policy_history_length=max_policy_history_length)
test_labels, test_features, test_seq_lengths =\
    sf.prepare_labels_features_lengths(policy_histories=policy_histories_test,
                                       policy_histories_lengths=policy_histories_length_test, 
                                       max_policy_history_length=max_policy_history_length)



Build TensorFlow graph with RNN

In [5]:
import tensorflow as tf

tf.reset_default_graph()
tf.set_random_seed(42)

# Our hyperparameters
n_steps = max_policy_history_length
n_inputs = 2
n_neurons = 200
n_outputs = 2
learning_rate = 0.0001

# Placeholders for our input sequences
seq_length = tf.placeholder(tf.int32, [None], name="seq_length")
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs], name="X")
y = tf.placeholder(tf.int32, [None], name="y")

# A single RNN layer of n_neurons neurons
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32, sequence_length=seq_length)

# We feed the layer's output of the last timestep into a fully connected layer of 2 neurons
# (1 per class, troubled or not). Softmax layer is next
logits = tf.layers.dense(states, n_outputs)
y_pred = tf.argmax(tf.nn.softmax(logits), axis=1)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)

# Loss function and Adam Optimizer
loss = tf.reduce_mean(tf.cast(xentropy, tf.float32))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

correct = tf.nn.in_top_k(logits, y, 1)
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

init = tf.global_variables_initializer()

accuracy_summary = tf.summary.scalar('Accuracy', accuracy)
loss_summary = tf.summary.scalar('Loss', loss)

file_writer = tf.summary.FileWriter(log_dir, tf.get_default_graph())

In [6]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

n_epochs = 100
batch_size = 200

train_data = sf.TrainDataSet(train_labels=train_labels, train_features=train_features, train_seq_lengths=train_seq_lengths)

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for i in range(train_data.num_examples // batch_size):
            y_batch, X_batch, seq_length_batch = train_data.next_batch(batch_size)
            
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})

        y_train_pred = y_pred.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        y_test_pred = y_pred.eval(feed_dict={X: test_features, y: test_labels, seq_length: test_seq_lengths})
        acc_train = accuracy.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        acc_test = accuracy.eval(feed_dict={X: test_features, y: test_labels, seq_length: test_seq_lengths})

        print(epoch, "Train accuracy:", acc_train, "Test accuracy:", acc_test)
        print(confusion_matrix(y_batch, y_train_pred))
        print(classification_report(y_batch, y_train_pred, target_names=['ok', 'troubled']))

        loss_summary_str = loss_summary.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        accuracy_summary_str = accuracy_summary.eval(feed_dict={X: X_batch, y: y_batch, seq_length: seq_length_batch})
        file_writer.add_summary(loss_summary_str, epoch)
        file_writer.add_summary(accuracy_summary_str, epoch)

file_writer.close()

0 Train accuracy: 0.855 Test accuracy: 0.859
[[147  11]
 [ 18  24]]
             precision    recall  f1-score   support

         ok       0.89      0.93      0.91       158
   troubled       0.69      0.57      0.62        42

avg / total       0.85      0.85      0.85       200



1 Train accuracy: 0.905 Test accuracy: 0.882
[[151   7]
 [ 12  30]]
             precision    recall  f1-score   support

         ok       0.93      0.96      0.94       158
   troubled       0.81      0.71      0.76        42

avg / total       0.90      0.91      0.90       200



2 Train accuracy: 0.945 Test accuracy: 0.9415
[[151   2]
 [  9  38]]
             precision    recall  f1-score   support

         ok       0.94      0.99      0.96       153
   troubled       0.95      0.81      0.87        47

avg / total       0.95      0.94      0.94       200



3 Train accuracy: 0.94 Test accuracy: 0.9405
[[153   0]
 [ 12  35]]
             precision    recall  f1-score   support

         ok       0.93      1.00      0.96       153
   troubled       1.00      0.74      0.85        47

avg / total       0.94      0.94      0.94       200



4 Train accuracy: 0.96 Test accuracy: 0.965
[[151   0]
 [  8  41]]
             precision    recall  f1-score   support

         ok       0.95      1.00      0.97       151
   troubled       1.00      0.84      0.91        49

avg / total       0.96      0.96      0.96       200



5 Train accuracy: 0.945 Test accuracy: 0.967
[[147   4]
 [  7  42]]
             precision    recall  f1-score   support

         ok       0.95      0.97      0.96       151
   troubled       0.91      0.86      0.88        49

avg / total       0.94      0.94      0.94       200



6 Train accuracy: 0.965 Test accuracy: 0.9565
[[164   0]
 [  7  29]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       164
   troubled       1.00      0.81      0.89        36

avg / total       0.97      0.96      0.96       200



7 Train accuracy: 0.955 Test accuracy: 0.9465
[[152   4]
 [  5  39]]
             precision    recall  f1-score   support

         ok       0.97      0.97      0.97       156
   troubled       0.91      0.89      0.90        44

avg / total       0.95      0.95      0.95       200



8 Train accuracy: 0.965 Test accuracy: 0.9635
[[143   4]
 [  3  50]]
             precision    recall  f1-score   support

         ok       0.98      0.97      0.98       147
   troubled       0.93      0.94      0.93        53

avg / total       0.97      0.96      0.97       200



9 Train accuracy: 0.98 Test accuracy: 0.977
[[150   1]
 [  3  46]]
             precision    recall  f1-score   support

         ok       0.98      0.99      0.99       151
   troubled       0.98      0.94      0.96        49

avg / total       0.98      0.98      0.98       200



10 Train accuracy: 0.99 Test accuracy: 0.975
[[154   0]
 [  2  44]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       154
   troubled       1.00      0.96      0.98        46

avg / total       0.99      0.99      0.99       200



11 Train accuracy: 0.985 Test accuracy: 0.979
[[154   0]
 [  3  43]]
             precision    recall  f1-score   support

         ok       0.98      1.00      0.99       154
   troubled       1.00      0.93      0.97        46

avg / total       0.99      0.98      0.98       200



12 Train accuracy: 0.98 Test accuracy: 0.976
[[152   1]
 [  3  44]]
             precision    recall  f1-score   support

         ok       0.98      0.99      0.99       153
   troubled       0.98      0.94      0.96        47

avg / total       0.98      0.98      0.98       200



13 Train accuracy: 0.99 Test accuracy: 0.9945
[[150   1]
 [  1  48]]
             precision    recall  f1-score   support

         ok       0.99      0.99      0.99       151
   troubled       0.98      0.98      0.98        49

avg / total       0.99      0.99      0.99       200



14 Train accuracy: 1.0 Test accuracy: 0.998
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



15 Train accuracy: 1.0 Test accuracy: 0.996
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



16 Train accuracy: 0.89 Test accuracy: 0.834
[[128  22]
 [  0  50]]
             precision    recall  f1-score   support

         ok       1.00      0.85      0.92       150
   troubled       0.69      1.00      0.82        50

avg / total       0.92      0.89      0.90       200



17 Train accuracy: 0.99 Test accuracy: 0.9915
[[161   0]
 [  2  37]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       161
   troubled       1.00      0.95      0.97        39

avg / total       0.99      0.99      0.99       200



18 Train accuracy: 1.0 Test accuracy: 0.998
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



19 Train accuracy: 1.0 Test accuracy: 0.996
[[156   0]
 [  0  44]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       156
   troubled       1.00      1.00      1.00        44

avg / total       1.00      1.00      1.00       200



20 Train accuracy: 0.99 Test accuracy: 0.9985
[[155   0]
 [  2  43]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       155
   troubled       1.00      0.96      0.98        45

avg / total       0.99      0.99      0.99       200



21 Train accuracy: 0.995 Test accuracy: 0.9975
[[165   1]
 [  0  34]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       166
   troubled       0.97      1.00      0.99        34

avg / total       1.00      0.99      1.00       200



22 Train accuracy: 0.995 Test accuracy: 0.9995
[[137   0]
 [  1  62]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       137
   troubled       1.00      0.98      0.99        63

avg / total       1.00      0.99      0.99       200



23 Train accuracy: 1.0 Test accuracy: 0.9965
[[155   0]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       155
   troubled       1.00      1.00      1.00        45

avg / total       1.00      1.00      1.00       200



24 Train accuracy: 1.0 Test accuracy: 0.984
[[152   0]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       152
   troubled       1.00      1.00      1.00        48

avg / total       1.00      1.00      1.00       200



25 Train accuracy: 1.0 Test accuracy: 0.999
[[164   0]
 [  0  36]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       164
   troubled       1.00      1.00      1.00        36

avg / total       1.00      1.00      1.00       200



26 Train accuracy: 0.995 Test accuracy: 0.9915
[[144   0]
 [  1  55]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       144
   troubled       1.00      0.98      0.99        56

avg / total       1.00      0.99      0.99       200



27 Train accuracy: 0.99 Test accuracy: 0.9965
[[152   0]
 [  2  46]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       152
   troubled       1.00      0.96      0.98        48

avg / total       0.99      0.99      0.99       200



28 Train accuracy: 0.99 Test accuracy: 0.9975
[[156   1]
 [  1  42]]
             precision    recall  f1-score   support

         ok       0.99      0.99      0.99       157
   troubled       0.98      0.98      0.98        43

avg / total       0.99      0.99      0.99       200



29 Train accuracy: 1.0 Test accuracy: 0.9965
[[157   0]
 [  0  43]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       157
   troubled       1.00      1.00      1.00        43

avg / total       1.00      1.00      1.00       200



30 Train accuracy: 1.0 Test accuracy: 0.9995
[[166   0]
 [  0  34]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       166
   troubled       1.00      1.00      1.00        34

avg / total       1.00      1.00      1.00       200



31 Train accuracy: 0.995 Test accuracy: 0.9965
[[162   0]
 [  1  37]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       162
   troubled       1.00      0.97      0.99        38

avg / total       1.00      0.99      0.99       200



32 Train accuracy: 0.995 Test accuracy: 0.9995
[[151   0]
 [  1  48]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       151
   troubled       1.00      0.98      0.99        49

avg / total       1.00      0.99      0.99       200



33 Train accuracy: 0.995 Test accuracy: 0.998
[[149   0]
 [  1  50]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       149
   troubled       1.00      0.98      0.99        51

avg / total       1.00      0.99      0.99       200



34 Train accuracy: 0.995 Test accuracy: 0.997
[[150   0]
 [  1  49]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       150
   troubled       1.00      0.98      0.99        50

avg / total       1.00      0.99      0.99       200



35 Train accuracy: 0.975 Test accuracy: 0.9775
[[141   5]
 [  0  54]]
             precision    recall  f1-score   support

         ok       1.00      0.97      0.98       146
   troubled       0.92      1.00      0.96        54

avg / total       0.98      0.97      0.98       200



36 Train accuracy: 1.0 Test accuracy: 0.9945
[[146   0]
 [  0  54]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       146
   troubled       1.00      1.00      1.00        54

avg / total       1.00      1.00      1.00       200



37 Train accuracy: 0.995 Test accuracy: 0.9925
[[153   0]
 [  1  46]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       153
   troubled       1.00      0.98      0.99        47

avg / total       1.00      0.99      0.99       200



38 Train accuracy: 0.995 Test accuracy: 0.9995
[[151   0]
 [  1  48]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       151
   troubled       1.00      0.98      0.99        49

avg / total       1.00      0.99      0.99       200



39 Train accuracy: 1.0 Test accuracy: 1.0
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



40 Train accuracy: 1.0 Test accuracy: 0.999
[[146   0]
 [  0  54]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       146
   troubled       1.00      1.00      1.00        54

avg / total       1.00      1.00      1.00       200



41 Train accuracy: 0.995 Test accuracy: 0.9985
[[154   0]
 [  1  45]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       154
   troubled       1.00      0.98      0.99        46

avg / total       1.00      0.99      0.99       200



42 Train accuracy: 1.0 Test accuracy: 0.998
[[145   0]
 [  0  55]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       145
   troubled       1.00      1.00      1.00        55

avg / total       1.00      1.00      1.00       200



43 Train accuracy: 0.995 Test accuracy: 1.0
[[158   1]
 [  0  41]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       159
   troubled       0.98      1.00      0.99        41

avg / total       1.00      0.99      1.00       200



44 Train accuracy: 1.0 Test accuracy: 0.999
[[152   0]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       152
   troubled       1.00      1.00      1.00        48

avg / total       1.00      1.00      1.00       200



45 Train accuracy: 1.0 Test accuracy: 0.999
[[168   0]
 [  0  32]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       168
   troubled       1.00      1.00      1.00        32

avg / total       1.00      1.00      1.00       200



46 Train accuracy: 0.995 Test accuracy: 0.999
[[155   1]
 [  0  44]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       156
   troubled       0.98      1.00      0.99        44

avg / total       1.00      0.99      1.00       200



47 Train accuracy: 0.99 Test accuracy: 0.988
[[148   0]
 [  2  50]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       148
   troubled       1.00      0.96      0.98        52

avg / total       0.99      0.99      0.99       200



48 Train accuracy: 1.0 Test accuracy: 0.999
[[166   0]
 [  0  34]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       166
   troubled       1.00      1.00      1.00        34

avg / total       1.00      1.00      1.00       200



49 Train accuracy: 0.995 Test accuracy: 0.98
[[151   1]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       152
   troubled       0.98      1.00      0.99        48

avg / total       1.00      0.99      1.00       200



50 Train accuracy: 0.995 Test accuracy: 0.9985
[[154   0]
 [  1  45]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       154
   troubled       1.00      0.98      0.99        46

avg / total       1.00      0.99      0.99       200



51 Train accuracy: 1.0 Test accuracy: 0.9995
[[162   0]
 [  0  38]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       162
   troubled       1.00      1.00      1.00        38

avg / total       1.00      1.00      1.00       200



52 Train accuracy: 1.0 Test accuracy: 0.9925
[[165   0]
 [  0  35]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       165
   troubled       1.00      1.00      1.00        35

avg / total       1.00      1.00      1.00       200



53 Train accuracy: 1.0 Test accuracy: 0.9995
[[162   0]
 [  0  38]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       162
   troubled       1.00      1.00      1.00        38

avg / total       1.00      1.00      1.00       200



54 Train accuracy: 1.0 Test accuracy: 0.999
[[149   0]
 [  0  51]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       149
   troubled       1.00      1.00      1.00        51

avg / total       1.00      1.00      1.00       200



55 Train accuracy: 1.0 Test accuracy: 0.9995
[[156   0]
 [  0  44]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       156
   troubled       1.00      1.00      1.00        44

avg / total       1.00      1.00      1.00       200



56 Train accuracy: 1.0 Test accuracy: 0.9995
[[155   0]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       155
   troubled       1.00      1.00      1.00        45

avg / total       1.00      1.00      1.00       200



57 Train accuracy: 1.0 Test accuracy: 0.9995
[[145   0]
 [  0  55]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       145
   troubled       1.00      1.00      1.00        55

avg / total       1.00      1.00      1.00       200



58 Train accuracy: 1.0 Test accuracy: 0.9995
[[150   0]
 [  0  50]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       150
   troubled       1.00      1.00      1.00        50

avg / total       1.00      1.00      1.00       200



59 Train accuracy: 0.82 Test accuracy: 0.7745
[[164   0]
 [ 36   0]]
             precision    recall  f1-score   support

         ok       0.82      1.00      0.90       164
   troubled       0.00      0.00      0.00        36

avg / total       0.67      0.82      0.74       200



/Users/gopora/MyStuff/Dev/miniconda3/envs/pie35/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


60 Train accuracy: 0.965 Test accuracy: 0.99
[[158   0]
 [  7  35]]
             precision    recall  f1-score   support

         ok       0.96      1.00      0.98       158
   troubled       1.00      0.83      0.91        42

avg / total       0.97      0.96      0.96       200



61 Train accuracy: 1.0 Test accuracy: 0.998
[[165   0]
 [  0  35]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       165
   troubled       1.00      1.00      1.00        35

avg / total       1.00      1.00      1.00       200



62 Train accuracy: 1.0 Test accuracy: 0.993
[[144   0]
 [  0  56]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       144
   troubled       1.00      1.00      1.00        56

avg / total       1.00      1.00      1.00       200



63 Train accuracy: 0.995 Test accuracy: 0.9975
[[153   1]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       154
   troubled       0.98      1.00      0.99        46

avg / total       1.00      0.99      1.00       200



64 Train accuracy: 1.0 Test accuracy: 0.999
[[156   0]
 [  0  44]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       156
   troubled       1.00      1.00      1.00        44

avg / total       1.00      1.00      1.00       200



65 Train accuracy: 1.0 Test accuracy: 0.998
[[159   0]
 [  0  41]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       159
   troubled       1.00      1.00      1.00        41

avg / total       1.00      1.00      1.00       200



66 Train accuracy: 1.0 Test accuracy: 0.999
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



67 Train accuracy: 1.0 Test accuracy: 0.9995
[[159   0]
 [  0  41]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       159
   troubled       1.00      1.00      1.00        41

avg / total       1.00      1.00      1.00       200



68 Train accuracy: 0.99 Test accuracy: 0.998
[[146   0]
 [  2  52]]
             precision    recall  f1-score   support

         ok       0.99      1.00      0.99       146
   troubled       1.00      0.96      0.98        54

avg / total       0.99      0.99      0.99       200



69 Train accuracy: 1.0 Test accuracy: 0.9985
[[150   0]
 [  0  50]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       150
   troubled       1.00      1.00      1.00        50

avg / total       1.00      1.00      1.00       200



70 Train accuracy: 1.0 Test accuracy: 0.9985
[[159   0]
 [  0  41]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       159
   troubled       1.00      1.00      1.00        41

avg / total       1.00      1.00      1.00       200



71 Train accuracy: 1.0 Test accuracy: 0.9995
[[146   0]
 [  0  54]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       146
   troubled       1.00      1.00      1.00        54

avg / total       1.00      1.00      1.00       200



72 Train accuracy: 1.0 Test accuracy: 0.9975
[[155   0]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       155
   troubled       1.00      1.00      1.00        45

avg / total       1.00      1.00      1.00       200



73 Train accuracy: 1.0 Test accuracy: 0.997
[[163   0]
 [  0  37]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       163
   troubled       1.00      1.00      1.00        37

avg / total       1.00      1.00      1.00       200



74 Train accuracy: 1.0 Test accuracy: 0.9975
[[158   0]
 [  0  42]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       158
   troubled       1.00      1.00      1.00        42

avg / total       1.00      1.00      1.00       200



75 Train accuracy: 1.0 Test accuracy: 0.9995
[[154   0]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       154
   troubled       1.00      1.00      1.00        46

avg / total       1.00      1.00      1.00       200



76 Train accuracy: 1.0 Test accuracy: 0.9995
[[161   0]
 [  0  39]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       161
   troubled       1.00      1.00      1.00        39

avg / total       1.00      1.00      1.00       200



77 Train accuracy: 0.995 Test accuracy: 0.9995
[[150   0]
 [  1  49]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       150
   troubled       1.00      0.98      0.99        50

avg / total       1.00      0.99      0.99       200



78 Train accuracy: 1.0 Test accuracy: 0.9995
[[162   0]
 [  0  38]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       162
   troubled       1.00      1.00      1.00        38

avg / total       1.00      1.00      1.00       200



79 Train accuracy: 1.0 Test accuracy: 0.999
[[146   0]
 [  0  54]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       146
   troubled       1.00      1.00      1.00        54

avg / total       1.00      1.00      1.00       200



80 Train accuracy: 1.0 Test accuracy: 0.9995
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



81 Train accuracy: 0.995 Test accuracy: 0.9975
[[152   0]
 [  1  47]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       152
   troubled       1.00      0.98      0.99        48

avg / total       1.00      0.99      0.99       200



82 Train accuracy: 0.995 Test accuracy: 0.9955
[[157   1]
 [  0  42]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       158
   troubled       0.98      1.00      0.99        42

avg / total       1.00      0.99      1.00       200



83 Train accuracy: 0.995 Test accuracy: 0.9985
[[142   0]
 [  1  57]]
             precision    recall  f1-score   support

         ok       0.99      1.00      1.00       142
   troubled       1.00      0.98      0.99        58

avg / total       1.00      0.99      0.99       200



84 Train accuracy: 1.0 Test accuracy: 0.9985
[[158   0]
 [  0  42]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       158
   troubled       1.00      1.00      1.00        42

avg / total       1.00      1.00      1.00       200



85 Train accuracy: 1.0 Test accuracy: 0.9995
[[155   0]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       155
   troubled       1.00      1.00      1.00        45

avg / total       1.00      1.00      1.00       200



86 Train accuracy: 1.0 Test accuracy: 0.9995
[[152   0]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       152
   troubled       1.00      1.00      1.00        48

avg / total       1.00      1.00      1.00       200



87 Train accuracy: 1.0 Test accuracy: 0.9995
[[148   0]
 [  0  52]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       148
   troubled       1.00      1.00      1.00        52

avg / total       1.00      1.00      1.00       200



88 Train accuracy: 1.0 Test accuracy: 0.9995
[[144   0]
 [  0  56]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       144
   troubled       1.00      1.00      1.00        56

avg / total       1.00      1.00      1.00       200



89 Train accuracy: 1.0 Test accuracy: 0.9995
[[149   0]
 [  0  51]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       149
   troubled       1.00      1.00      1.00        51

avg / total       1.00      1.00      1.00       200



90 Train accuracy: 1.0 Test accuracy: 0.9985
[[161   0]
 [  0  39]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       161
   troubled       1.00      1.00      1.00        39

avg / total       1.00      1.00      1.00       200



91 Train accuracy: 0.995 Test accuracy: 0.9985
[[154   1]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       155
   troubled       0.98      1.00      0.99        45

avg / total       1.00      0.99      1.00       200



92 Train accuracy: 1.0 Test accuracy: 0.9995
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



93 Train accuracy: 1.0 Test accuracy: 0.999
[[152   0]
 [  0  48]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       152
   troubled       1.00      1.00      1.00        48

avg / total       1.00      1.00      1.00       200



94 Train accuracy: 1.0 Test accuracy: 0.9975
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



95 Train accuracy: 0.995 Test accuracy: 0.9975
[[153   1]
 [  0  46]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       154
   troubled       0.98      1.00      0.99        46

avg / total       1.00      0.99      1.00       200



96 Train accuracy: 0.995 Test accuracy: 0.996
[[154   1]
 [  0  45]]
             precision    recall  f1-score   support

         ok       1.00      0.99      1.00       155
   troubled       0.98      1.00      0.99        45

avg / total       1.00      0.99      1.00       200



97 Train accuracy: 1.0 Test accuracy: 0.9985
[[151   0]
 [  0  49]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       151
   troubled       1.00      1.00      1.00        49

avg / total       1.00      1.00      1.00       200



98 Train accuracy: 1.0 Test accuracy: 0.9995
[[142   0]
 [  0  58]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       142
   troubled       1.00      1.00      1.00        58

avg / total       1.00      1.00      1.00       200



99 Train accuracy: 1.0 Test accuracy: 1.0
[[156   0]
 [  0  44]]
             precision    recall  f1-score   support

         ok       1.00      1.00      1.00       156
   troubled       1.00      1.00      1.00        44

avg / total       1.00      1.00      1.00       200

